CREATE TYPE episode_lifecycle_status AS ENUM ('open', 'active', 'closed');
CREATE TYPE episode_event_status AS ENUM ('current', 'deletion_pending', 'deleted');
CREATE TYPE event_draft_intent AS ENUM ('create', 'update');
CREATE TYPE event_draft_mode AS ENUM ('autosave', 'manual');

INSERT INTO permissions (name, description) VALUES
    ('episode.read', 'Read episode and minimum-disclosure event headers'),
    ('episode.read.override', 'Read an episode outside ordinary site or firm scope with a reason'),
    ('episode.create', 'Create an episode in the server-derived clinical context'),
    ('episode.update', 'Update or close an authorized episode'),
    ('episode.reopen', 'Reopen an authorized closed episode with a reason'),
    ('event_draft.create', 'Create an authorized clinician-owned event draft'),
    ('event_draft.read', 'Read an authorized clinician-owned event draft'),
    ('event_draft.update', 'Update an authorized clinician-owned event draft'),
    ('event_draft.abandon', 'Audited soft deletion of an authorized clinician-owned event draft')
ON CONFLICT (name) DO NOTHING;

-- The historic patient-institution association is retained even if it later
-- becomes inactive. This key lets episode rows prove the patient/institution
-- pair without relying on a partial unique index.
ALTER TABLE patient_institutions
    ADD CONSTRAINT patient_institutions_id_patient_institution_unique
    UNIQUE (id, patient_id, institution_id);

CREATE TABLE episodes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    patient_id BIGINT NOT NULL REFERENCES patients(id),
    institution_id BIGINT NOT NULL REFERENCES institutions(id),
    patient_institution_id BIGINT NOT NULL,
    site_id BIGINT NOT NULL,
    firm_id BIGINT NOT NULL REFERENCES firms(id),
    status episode_lifecycle_status NOT NULL,
    started_at TIMESTAMPTZ,
    ended_at TIMESTAMPTZ,
    support_services BOOLEAN NOT NULL DEFAULT FALSE,
    change_tracker BOOLEAN NOT NULL DEFAULT FALSE,
    version BIGINT NOT NULL DEFAULT 1 CHECK (version >= 1),
    created_by_user_id BIGINT REFERENCES users(id),
    updated_by_user_id BIGINT REFERENCES users(id),
    deleted_at TIMESTAMPTZ,
    deleted_by_user_id BIGINT REFERENCES users(id),
    deleted_reason TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    FOREIGN KEY (patient_institution_id, patient_id, institution_id)
        REFERENCES patient_institutions(id, patient_id, institution_id),
    FOREIGN KEY (site_id, institution_id) REFERENCES sites(id, institution_id),
    UNIQUE (id, patient_id, institution_id, site_id, firm_id),
    CHECK (substring(public_id::text FROM 15 FOR 1) = '4'),
    CHECK (substring(public_id::text FROM 20 FOR 1) IN ('8', '9', 'a', 'b')),
    CHECK (ended_at IS NULL OR started_at IS NULL OR ended_at >= started_at),
    CHECK ((status = 'closed') = (ended_at IS NOT NULL)),
    CHECK ((deleted_at IS NULL) = (deleted_by_user_id IS NULL)),
    CHECK (deleted_reason IS NULL OR (btrim(deleted_reason) <> '' AND char_length(deleted_reason) <= 2000)),
    CHECK (deleted_at IS NULL OR deleted_reason IS NOT NULL),
    CHECK (updated_at >= created_at)
);

CREATE INDEX episodes_patient_timeline_idx
    ON episodes (patient_id, started_at DESC NULLS LAST, id DESC)
    WHERE deleted_at IS NULL;

CREATE INDEX episodes_scope_status_idx
    ON episodes (institution_id, site_id, firm_id, status, id)
    WHERE deleted_at IS NULL;

CREATE TABLE episode_audit_sequences (
    episode_id BIGINT PRIMARY KEY REFERENCES episodes(id),
    next_value BIGINT NOT NULL DEFAULT 1 CHECK (next_value >= 1),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    episode_id BIGINT,
    patient_id BIGINT NOT NULL REFERENCES patients(id),
    institution_id BIGINT NOT NULL REFERENCES institutions(id),
    patient_institution_id BIGINT NOT NULL,
    site_id BIGINT NOT NULL,
    firm_id BIGINT NOT NULL REFERENCES firms(id),
    event_type_code TEXT NOT NULL CHECK (
        event_type_code = btrim(event_type_code)
        AND event_type_code <> ''
        AND char_length(event_type_code) <= 100
    ),
    occurred_at TIMESTAMPTZ NOT NULL,
    status episode_event_status NOT NULL DEFAULT 'current',
    deletion_reason TEXT,
    is_imported_orphan BOOLEAN NOT NULL DEFAULT FALSE,
    -- Future event-write contracts must derive this server-side; no client
    -- request is authorized to claim automated provenance.
    is_automated BOOLEAN NOT NULL DEFAULT FALSE,
    automated_source JSONB,
    version BIGINT NOT NULL DEFAULT 1 CHECK (version >= 1),
    created_by_user_id BIGINT REFERENCES users(id),
    updated_by_user_id BIGINT REFERENCES users(id),
    deleted_at TIMESTAMPTZ,
    deleted_by_user_id BIGINT REFERENCES users(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    FOREIGN KEY (episode_id, patient_id, institution_id, site_id, firm_id)
        REFERENCES episodes(id, patient_id, institution_id, site_id, firm_id),
    FOREIGN KEY (patient_institution_id, patient_id, institution_id)
        REFERENCES patient_institutions(id, patient_id, institution_id),
    FOREIGN KEY (site_id, institution_id) REFERENCES sites(id, institution_id),
    UNIQUE (id, episode_id, patient_id, institution_id, site_id, firm_id),
    UNIQUE (id, episode_id),
    CHECK (substring(public_id::text FROM 15 FOR 1) = '4'),
    CHECK (substring(public_id::text FROM 20 FOR 1) IN ('8', '9', 'a', 'b')),
    CHECK (automated_source IS NULL OR jsonb_typeof(automated_source) = 'object'),
    CHECK ((episode_id IS NULL) = is_imported_orphan),
    CHECK ((status = 'deleted') = (deleted_at IS NOT NULL)),
    CHECK (deletion_reason IS NULL OR (
        status IN ('deletion_pending', 'deleted')
        AND btrim(deletion_reason) <> ''
        AND char_length(deletion_reason) <= 2000
    )),
    CHECK (status <> 'deletion_pending' OR deletion_reason IS NOT NULL),
    CHECK (status <> 'deleted' OR (
        deleted_by_user_id IS NOT NULL
        AND deletion_reason IS NOT NULL
        AND btrim(deletion_reason) <> ''
    )),
    CHECK ((deleted_at IS NULL) = (deleted_by_user_id IS NULL)),
    CHECK (updated_at >= created_at)
);

CREATE INDEX events_episode_timeline_idx
    ON events (episode_id, occurred_at DESC, id DESC)
    WHERE status = 'current' AND deleted_at IS NULL;

CREATE INDEX events_scope_header_idx
    ON events (institution_id, site_id, firm_id, occurred_at DESC, id DESC)
    WHERE status = 'current' AND deleted_at IS NULL;

CREATE INDEX events_patient_timeline_idx
    ON events (patient_id, occurred_at DESC, id DESC)
    WHERE status = 'current' AND deleted_at IS NULL;

CREATE TABLE event_versions (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL,
    episode_id BIGINT NOT NULL REFERENCES episodes(id),
    episode_audit_sequence BIGINT NOT NULL CHECK (episode_audit_sequence >= 1),
    previous_version BIGINT,
    resulting_version BIGINT NOT NULL CHECK (resulting_version >= 1),
    command TEXT NOT NULL CHECK (btrim(command) <> '' AND char_length(command) <= 100),
    actor_user_id BIGINT REFERENCES users(id),
    session_id BIGINT REFERENCES sessions(id),
    correlation_id TEXT NOT NULL CHECK (btrim(correlation_id) <> '' AND char_length(correlation_id) <= 200),
    reason TEXT,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    FOREIGN KEY (event_id, episode_id) REFERENCES events(id, episode_id),
    UNIQUE (episode_id, episode_audit_sequence),
    CHECK (previous_version IS NULL OR previous_version >= 1),
    CHECK (
        (previous_version IS NULL AND resulting_version = 1)
        OR (previous_version IS NOT NULL AND resulting_version = previous_version + 1)
    ),
    CHECK (jsonb_typeof(metadata) = 'object'),
    CHECK (actor_user_id IS NOT NULL OR session_id IS NOT NULL),
    CHECK (reason IS NULL OR (btrim(reason) <> '' AND char_length(reason) <= 2000))
);

CREATE INDEX event_versions_event_idx ON event_versions (event_id, occurred_at DESC);

CREATE FUNCTION reject_event_version_mutation() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION 'event_versions is append-only';
END;
$$;

CREATE TRIGGER event_versions_no_update_or_delete
BEFORE UPDATE OR DELETE ON event_versions
FOR EACH ROW EXECUTE FUNCTION reject_event_version_mutation();

CREATE TRIGGER event_versions_no_truncate
BEFORE TRUNCATE ON event_versions
FOR EACH STATEMENT EXECUTE FUNCTION reject_event_version_mutation();

CREATE FUNCTION reject_disposed_event_draft_mutation() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    IF OLD.deleted_at IS NOT NULL THEN
        RAISE EXCEPTION 'disposed event_drafts are immutable';
    END IF;
    RETURN NEW;
END;
$$;

CREATE TABLE event_drafts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    owner_user_id BIGINT NOT NULL REFERENCES users(id),
    episode_id BIGINT NOT NULL,
    patient_id BIGINT NOT NULL,
    institution_id BIGINT NOT NULL,
    site_id BIGINT NOT NULL,
    firm_id BIGINT NOT NULL,
    event_type_code TEXT NOT NULL CHECK (
        event_type_code = btrim(event_type_code)
        AND event_type_code <> ''
        AND char_length(event_type_code) <= 100
    ),
    target_event_id BIGINT,
    intent event_draft_intent NOT NULL DEFAULT 'create',
    mode event_draft_mode NOT NULL,
    schema_version INTEGER NOT NULL CHECK (schema_version >= 1),
    payload JSONB NOT NULL,
    version BIGINT NOT NULL DEFAULT 1 CHECK (version >= 1),
    expires_at TIMESTAMPTZ NOT NULL,
    deleted_at TIMESTAMPTZ,
    deleted_by_user_id BIGINT REFERENCES users(id),
    disposal_reason TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    FOREIGN KEY (episode_id, patient_id, institution_id, site_id, firm_id)
        REFERENCES episodes(id, patient_id, institution_id, site_id, firm_id),
    FOREIGN KEY (target_event_id, episode_id, patient_id, institution_id, site_id, firm_id)
        REFERENCES events(id, episode_id, patient_id, institution_id, site_id, firm_id),
    CHECK (substring(public_id::text FROM 15 FOR 1) = '4'),
    CHECK (substring(public_id::text FROM 20 FOR 1) IN ('8', '9', 'a', 'b')),
    CHECK ((intent = 'update') = (target_event_id IS NOT NULL)),
    CHECK (jsonb_typeof(payload) = 'object'),
    -- JSONB normalizes input. The Go HTTP boundary additionally enforces the
    -- 64 KiB decoded request-body limit before persistence.
    CHECK (octet_length(payload::text) <= 65536),
    CHECK (expires_at > created_at),
    CHECK ((deleted_at IS NULL) = (deleted_by_user_id IS NULL)),
    CHECK (disposal_reason IS NULL OR disposal_reason IN ('abandoned', 'expired')),
    CHECK (deleted_at IS NULL OR disposal_reason IS NOT NULL),
    CHECK (updated_at >= created_at)
);

CREATE TRIGGER event_drafts_no_mutation_after_disposal
BEFORE UPDATE ON event_drafts
FOR EACH ROW EXECUTE FUNCTION reject_disposed_event_draft_mutation();

CREATE UNIQUE INDEX event_drafts_active_autosave_create_unique
    ON event_drafts (owner_user_id, episode_id, event_type_code)
    WHERE deleted_at IS NULL AND intent = 'create' AND mode = 'autosave';

CREATE UNIQUE INDEX event_drafts_active_update_unique
    ON event_drafts (owner_user_id, target_event_id)
    WHERE deleted_at IS NULL AND intent = 'update';

CREATE INDEX event_drafts_active_owner_idx
    ON event_drafts (owner_user_id, episode_id, updated_at DESC, id DESC)
    WHERE deleted_at IS NULL;

CREATE INDEX event_drafts_expiry_idx
    ON event_drafts (expires_at, id)
    WHERE deleted_at IS NULL;
