CREATE TYPE patient_gender AS ENUM (
    'female',
    'male',
    'other',
    'unknown'
);

CREATE TYPE patient_identifier_lifecycle AS ENUM (
    'active',
    'inactive',
    'deleted'
);

INSERT INTO permissions (name, description) VALUES
    ('patient.duplicate_check', 'Run exact-only duplicate checks in the current institution')
ON CONFLICT (name) DO NOTHING;

-- No existing production role receives patient.duplicate_check implicitly.
-- A later approved registration-role policy owns that mapping.

CREATE TABLE patients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    given_name TEXT,
    given_name_normalized TEXT COLLATE "C",
    family_name TEXT,
    family_name_normalized TEXT COLLATE "C",
    name_normalization_version SMALLINT NOT NULL DEFAULT 1
        CHECK (name_normalization_version >= 1),
    date_of_birth DATE NOT NULL,
    gender patient_gender NOT NULL,
    deceased BOOLEAN NOT NULL DEFAULT FALSE,
    date_of_death DATE,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    deleted_at TIMESTAMPTZ,
    source_system TEXT NOT NULL CHECK (btrim(source_system) <> ''),
    source_record_id TEXT NOT NULL CHECK (btrim(source_record_id) <> ''),
    source_revision TEXT,
    source_checksum TEXT,
    version BIGINT NOT NULL DEFAULT 1 CHECK (version >= 1),
    created_by_user_id BIGINT REFERENCES users(id),
    updated_by_user_id BIGINT REFERENCES users(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (source_system, source_record_id),
    CHECK (substring(public_id::text FROM 15 FOR 1) = '4'),
    CHECK (substring(public_id::text FROM 20 FOR 1) IN ('8', '9', 'a', 'b')),
    CHECK (given_name IS NULL OR (given_name <> '' AND char_length(given_name) <= 300)),
    CHECK (family_name IS NULL OR (family_name <> '' AND char_length(family_name) <= 100)),
    CHECK ((given_name IS NULL) = (given_name_normalized IS NULL)),
    CHECK ((family_name IS NULL) = (family_name_normalized IS NULL)),
    CHECK (given_name_normalized IS NULL OR given_name_normalized <> ''),
    CHECK (family_name_normalized IS NULL OR family_name_normalized <> ''),
    CHECK (date_of_death IS NULL OR deceased),
    CHECK (date_of_death IS NULL OR date_of_death >= date_of_birth),
    CHECK (active OR deleted_at IS NOT NULL),
    CHECK (NOT active OR deleted_at IS NULL),
    CHECK (updated_at >= created_at)
);

CREATE TABLE patient_institutions (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    patient_id BIGINT NOT NULL REFERENCES patients(id),
    institution_id BIGINT NOT NULL REFERENCES institutions(id),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    primary_association BOOLEAN NOT NULL DEFAULT FALSE,
    association_source TEXT NOT NULL CHECK (
        association_source IN (
            'legacy_primary',
            'approved_deployment_default',
            'verified_legacy_association',
            'visionopus'
        )
    ),
    effective_from TIMESTAMPTZ NOT NULL DEFAULT now(),
    effective_to TIMESTAMPTZ,
    created_by_user_id BIGINT REFERENCES users(id),
    updated_by_user_id BIGINT REFERENCES users(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CHECK (NOT primary_association OR active),
    CHECK (NOT active OR effective_to IS NULL),
    CHECK (effective_to IS NULL OR effective_to >= effective_from),
    CHECK (updated_at >= created_at)
);

CREATE INDEX patients_demographics_search_idx
    ON patients (
        family_name_normalized,
        date_of_birth,
        gender,
        given_name_normalized,
        public_id
    )
    WHERE active;

CREATE UNIQUE INDEX patient_institutions_active_pair_unique
    ON patient_institutions (patient_id, institution_id)
    WHERE active;

CREATE UNIQUE INDEX patient_institutions_active_primary_unique
    ON patient_institutions (patient_id)
    WHERE active AND primary_association;

CREATE INDEX patient_institutions_institution_patient_idx
    ON patient_institutions (institution_id, patient_id)
    WHERE active;

CREATE TABLE patient_identifier_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stable_code TEXT NOT NULL CHECK (stable_code ~ '^[a-z][a-z0-9_.-]*$'),
    institution_id BIGINT NOT NULL REFERENCES institutions(id),
    site_id BIGINT,
    display_label TEXT NOT NULL CHECK (
        display_label = btrim(display_label)
        AND display_label <> ''
        AND char_length(display_label) <= 100
    ),
    normalization_kind TEXT NOT NULL CHECK (
        normalization_kind IN (
            'nhs_number_v1',
            'exact_text_v1',
            'left_zero_pad_ascii_digits_v1'
        )
    ),
    validation_pattern TEXT,
    maximum_canonical_length SMALLINT NOT NULL
        CHECK (maximum_canonical_length BETWEEN 1 AND 255),
    zero_pad_width SMALLINT,
    validation_state TEXT NOT NULL CHECK (
        validation_state IN ('validated', 'quarantined')
    ),
    searchable BOOLEAN NOT NULL DEFAULT TRUE,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    display_order INTEGER NOT NULL CHECK (display_order >= 0),
    identifier_necessity TEXT NOT NULL DEFAULT 'optional' CHECK (
        identifier_necessity IN ('required', 'optional', 'not_used')
    ),
    status_necessity TEXT NOT NULL DEFAULT 'optional' CHECK (
        status_necessity IN ('required', 'optional', 'not_used')
    ),
    display_prefix TEXT NOT NULL DEFAULT '',
    display_suffix TEXT NOT NULL DEFAULT '',
    spacing_rule TEXT CHECK (spacing_rule IS NULL OR char_length(spacing_rule) <= 255),
    configuration_version BIGINT NOT NULL DEFAULT 1 CHECK (configuration_version >= 1),
    source_system TEXT NOT NULL CHECK (btrim(source_system) <> ''),
    source_record_id TEXT NOT NULL CHECK (btrim(source_record_id) <> ''),
    source_revision TEXT,
    created_by_user_id BIGINT REFERENCES users(id),
    updated_by_user_id BIGINT REFERENCES users(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    FOREIGN KEY (site_id, institution_id) REFERENCES sites(id, institution_id),
    UNIQUE NULLS NOT DISTINCT (institution_id, site_id, stable_code),
    UNIQUE (source_system, source_record_id),
    UNIQUE (id, institution_id),
    CHECK (NOT searchable OR active),
    CHECK (NOT active OR validation_state = 'validated'),
    CHECK (
        (normalization_kind = 'nhs_number_v1'
            AND validation_pattern IS NULL
            AND zero_pad_width IS NULL
            AND maximum_canonical_length = 10)
        OR
        (normalization_kind = 'exact_text_v1'
            AND validation_pattern IS NOT NULL
            AND btrim(validation_pattern) <> ''
            AND zero_pad_width IS NULL)
        OR
        (normalization_kind = 'left_zero_pad_ascii_digits_v1'
            AND validation_pattern IS NOT NULL
            AND btrim(validation_pattern) <> ''
            AND zero_pad_width IS NOT NULL
            AND zero_pad_width BETWEEN 1 AND maximum_canonical_length)
    ),
    CHECK (updated_at >= created_at)
);

CREATE UNIQUE INDEX patient_identifier_types_active_display_order_unique
    ON patient_identifier_types (institution_id, site_id, display_order)
    NULLS NOT DISTINCT
    WHERE active;

CREATE INDEX patient_identifier_types_scope_search_idx
    ON patient_identifier_types (institution_id, site_id, display_order)
    WHERE active AND searchable AND validation_state = 'validated';

CREATE TABLE patient_identifier_statuses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identifier_type_id BIGINT NOT NULL REFERENCES patient_identifier_types(id),
    stable_code TEXT NOT NULL CHECK (stable_code ~ '^[a-z][a-z0-9_.-]*$'),
    description TEXT NOT NULL CHECK (btrim(description) <> ''),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    source_system TEXT NOT NULL CHECK (btrim(source_system) <> ''),
    source_record_id TEXT NOT NULL CHECK (btrim(source_record_id) <> ''),
    created_by_user_id BIGINT REFERENCES users(id),
    updated_by_user_id BIGINT REFERENCES users(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (identifier_type_id, stable_code),
    UNIQUE (source_system, source_record_id),
    UNIQUE (id, identifier_type_id),
    CHECK (updated_at >= created_at)
);

CREATE INDEX patient_identifier_statuses_type_idx
    ON patient_identifier_statuses (identifier_type_id);

CREATE TABLE patient_identifiers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id BIGINT NOT NULL REFERENCES patients(id),
    identifier_type_id BIGINT NOT NULL REFERENCES patient_identifier_types(id),
    identifier_status_id BIGINT,
    original_value TEXT NOT NULL CHECK (
        original_value <> '' AND char_length(original_value) <= 255
    ),
    canonical_value TEXT NOT NULL COLLATE "C" CHECK (
        canonical_value <> '' AND char_length(canonical_value) <= 255
    ),
    source_marker TEXT NOT NULL CHECK (
        btrim(source_marker) <> '' AND char_length(source_marker) <= 255
    ),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    lifecycle patient_identifier_lifecycle NOT NULL DEFAULT 'active',
    deleted_at TIMESTAMPTZ,
    source_system TEXT NOT NULL CHECK (btrim(source_system) <> ''),
    source_record_id TEXT NOT NULL CHECK (btrim(source_record_id) <> ''),
    source_revision TEXT,
    version BIGINT NOT NULL DEFAULT 1 CHECK (version >= 1),
    created_by_user_id BIGINT REFERENCES users(id),
    updated_by_user_id BIGINT REFERENCES users(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    FOREIGN KEY (identifier_status_id, identifier_type_id)
        REFERENCES patient_identifier_statuses(id, identifier_type_id),
    UNIQUE (source_system, source_record_id),
    UNIQUE (patient_id, identifier_type_id, canonical_value),
    CHECK (
        (active AND lifecycle = 'active' AND deleted_at IS NULL)
        OR (NOT active AND lifecycle = 'inactive' AND deleted_at IS NULL)
        OR (NOT active AND lifecycle = 'deleted' AND deleted_at IS NOT NULL)
    ),
    CHECK (updated_at >= created_at)
);

CREATE UNIQUE INDEX patient_identifiers_active_patient_type_unique
    ON patient_identifiers (patient_id, identifier_type_id)
    WHERE active;

CREATE UNIQUE INDEX patient_identifiers_active_global_identity_unique
    ON patient_identifiers (identifier_type_id, canonical_value, source_marker)
    WHERE active;

CREATE INDEX patient_identifiers_patient_active_idx
    ON patient_identifiers (patient_id, identifier_type_id)
    WHERE active;

CREATE INDEX patient_identifiers_status_idx
    ON patient_identifiers (identifier_status_id)
    WHERE identifier_status_id IS NOT NULL;

CREATE TABLE patient_identifier_history (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    patient_id BIGINT NOT NULL REFERENCES patients(id),
    identifier_type_id BIGINT REFERENCES patient_identifier_types(id),
    identifier_type_code TEXT CHECK (
        identifier_type_code IS NULL OR char_length(identifier_type_code) <= 100
    ),
    original_value TEXT NOT NULL CHECK (
        original_value <> '' AND char_length(original_value) <= 255
    ),
    canonical_value TEXT COLLATE "C" CHECK (
        canonical_value IS NULL OR (canonical_value <> '' AND char_length(canonical_value) <= 255)
    ),
    lifecycle patient_identifier_lifecycle NOT NULL,
    recorded_at TIMESTAMPTZ,
    source_system TEXT NOT NULL CHECK (btrim(source_system) <> ''),
    source_table TEXT NOT NULL CHECK (btrim(source_table) <> ''),
    source_record_id TEXT NOT NULL CHECK (btrim(source_record_id) <> ''),
    source_revision TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (source_system, source_table, source_record_id),
    CHECK (
        identifier_type_id IS NOT NULL
        OR (identifier_type_code IS NOT NULL AND btrim(identifier_type_code) <> '')
    ),
    CHECK (lifecycle <> 'active')
);

CREATE INDEX patient_identifier_history_patient_idx
    ON patient_identifier_history (patient_id, recorded_at DESC);

CREATE TABLE patient_merge_lineage (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    source_patient_id BIGINT NOT NULL REFERENCES patients(id),
    target_patient_id BIGINT NOT NULL REFERENCES patients(id),
    merge_state TEXT NOT NULL CHECK (
        merge_state IN ('requested', 'completed', 'rejected', 'deleted', 'unknown')
    ),
    requested_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    source_system TEXT NOT NULL CHECK (btrim(source_system) <> ''),
    source_table TEXT NOT NULL CHECK (btrim(source_table) <> ''),
    source_record_id TEXT NOT NULL CHECK (btrim(source_record_id) <> ''),
    source_revision TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (source_system, source_table, source_record_id),
    CHECK (source_patient_id <> target_patient_id),
    CHECK (completed_at IS NULL OR requested_at IS NULL OR completed_at >= requested_at),
    CHECK ((merge_state = 'completed') = (completed_at IS NOT NULL))
);

CREATE INDEX patient_merge_lineage_source_idx
    ON patient_merge_lineage (source_patient_id);

CREATE INDEX patient_merge_lineage_target_idx
    ON patient_merge_lineage (target_patient_id);
