DROP TRIGGER IF EXISTS development_theatre_booking_audit_no_truncate ON development_theatre_booking_audit;
DROP TRIGGER IF EXISTS development_theatre_booking_audit_no_update_or_delete ON development_theatre_booking_audit;
DROP FUNCTION IF EXISTS reject_development_theatre_booking_audit_mutation();
DROP TABLE IF EXISTS development_theatre_booking_audit;
DROP TABLE IF EXISTS development_booking_requests;
DROP TABLE IF EXISTS development_theatre_sessions;
DROP TABLE IF EXISTS development_theatre_rooms;
DROP TYPE IF EXISTS development_booking_request_status;
DELETE FROM role_permissions WHERE permission_id IN (SELECT id FROM permissions WHERE name = 'theatre.development_booking.manage');
DELETE FROM permissions WHERE name = 'theatre.development_booking.manage';
