CREATE TYPE credential_state AS ENUM (
    'active',
    'soft_locked',
    'locked',
    'stale',
    'expired',
    'disabled',
    'reset_required'
);

CREATE TABLE institutions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL CHECK (btrim(name) <> ''),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE sites (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    institution_id BIGINT NOT NULL REFERENCES institutions(id),
    name TEXT NOT NULL CHECK (btrim(name) <> ''),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (institution_id, name),
    UNIQUE (id, institution_id)
);

CREATE TABLE firms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    institution_id BIGINT REFERENCES institutions(id),
    name TEXT NOT NULL CHECK (btrim(name) <> ''),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    global_access BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CHECK ((global_access AND institution_id IS NULL) OR (NOT global_access AND institution_id IS NOT NULL))
);

CREATE UNIQUE INDEX firms_institution_name_unique
    ON firms (institution_id, name)
    WHERE institution_id IS NOT NULL;

CREATE UNIQUE INDEX firms_global_name_unique
    ON firms (name)
    WHERE global_access;

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    display_name TEXT NOT NULL CHECK (btrim(display_name) <> ''),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    authorization_version BIGINT NOT NULL DEFAULT 1 CHECK (authorization_version >= 1),
    created_by_user_id BIGINT REFERENCES users(id),
    updated_by_user_id BIGINT REFERENCES users(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE user_institution_memberships (
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    institution_id BIGINT NOT NULL REFERENCES institutions(id),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    PRIMARY KEY (user_id, institution_id)
);

CREATE TABLE user_site_memberships (
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    site_id BIGINT NOT NULL REFERENCES sites(id),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    PRIMARY KEY (user_id, site_id)
);

CREATE TABLE user_firm_memberships (
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    firm_id BIGINT NOT NULL REFERENCES firms(id),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    PRIMARY KEY (user_id, firm_id)
);

CREATE TABLE user_firm_preferences (
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    firm_id BIGINT NOT NULL REFERENCES firms(id),
    position INTEGER NOT NULL CHECK (position >= 0),
    PRIMARY KEY (user_id, firm_id),
    UNIQUE (user_id, position)
);

CREATE TABLE authentication_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    institution_id BIGINT REFERENCES institutions(id),
    method TEXT NOT NULL CHECK (method IN ('LOCAL', 'LDAP', 'SSO')),
    name TEXT NOT NULL CHECK (btrim(name) <> ''),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (institution_id, method, name)
);

CREATE TABLE user_credentials (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    authentication_profile_id BIGINT REFERENCES authentication_profiles(id),
    canonical_username TEXT NOT NULL CHECK (canonical_username = lower(btrim(canonical_username))),
    password_hash TEXT,
    hash_scheme TEXT,
    hash_version INTEGER,
    state credential_state NOT NULL DEFAULT 'active',
    failed_attempts INTEGER NOT NULL DEFAULT 0 CHECK (failed_attempts >= 0),
    soft_locked_until TIMESTAMPTZ,
    password_changed_at TIMESTAMPTZ,
    last_succeeded_at TIMESTAMPTZ,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    version BIGINT NOT NULL DEFAULT 1 CHECK (version >= 1),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (canonical_username),
    CHECK ((password_hash IS NULL) = (hash_scheme IS NULL)),
    CHECK (authentication_profile_id IS NOT NULL OR (state = 'reset_required' AND NOT active))
);

CREATE TABLE permissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE CHECK (name ~ '^[a-z][a-z0-9_.]*$'),
    description TEXT NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE CHECK (btrim(name) <> ''),
    description TEXT NOT NULL,
    scope TEXT NOT NULL CHECK (scope IN ('global', 'institution')),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    UNIQUE (id, scope)
);

CREATE TABLE role_permissions (
    role_id BIGINT NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
    permission_id BIGINT NOT NULL REFERENCES permissions(id) ON DELETE CASCADE,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    PRIMARY KEY (role_id, permission_id)
);

CREATE TABLE user_role_assignments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    role_id BIGINT NOT NULL,
    role_scope TEXT NOT NULL,
    institution_id BIGINT REFERENCES institutions(id),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    assigned_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    assigned_by_user_id BIGINT REFERENCES users(id),
    FOREIGN KEY (role_id, role_scope) REFERENCES roles(id, scope),
    UNIQUE NULLS NOT DISTINCT (user_id, role_id, institution_id),
    CHECK (
        (role_scope = 'global' AND institution_id IS NULL)
        OR (role_scope = 'institution' AND institution_id IS NOT NULL)
    )
);

CREATE TABLE sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_digest BYTEA NOT NULL UNIQUE CHECK (octet_length(token_digest) = 32),
    csrf_digest BYTEA NOT NULL CHECK (octet_length(csrf_digest) = 32),
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    institution_id BIGINT NOT NULL REFERENCES institutions(id),
    site_id BIGINT NOT NULL,
    firm_id BIGINT NOT NULL REFERENCES firms(id),
    created_at TIMESTAMPTZ NOT NULL,
    last_seen_at TIMESTAMPTZ NOT NULL,
    idle_expires_at TIMESTAMPTZ NOT NULL,
    absolute_expires_at TIMESTAMPTZ NOT NULL,
    revoked_at TIMESTAMPTZ,
    revocation_reason TEXT,
    authorization_version BIGINT NOT NULL CHECK (authorization_version >= 1),
    context_version BIGINT NOT NULL DEFAULT 1 CHECK (context_version >= 1),
    version BIGINT NOT NULL DEFAULT 1 CHECK (version >= 1),
    FOREIGN KEY (site_id, institution_id) REFERENCES sites(id, institution_id),
    CHECK (idle_expires_at <= absolute_expires_at),
    CHECK ((revoked_at IS NULL) = (revocation_reason IS NULL))
);

CREATE INDEX sessions_user_active_idx
    ON sessions (user_id, absolute_expires_at)
    WHERE revoked_at IS NULL;

CREATE INDEX user_institution_memberships_institution_idx
    ON user_institution_memberships (institution_id);
CREATE INDEX user_site_memberships_site_idx ON user_site_memberships (site_id);
CREATE INDEX user_firm_memberships_firm_idx ON user_firm_memberships (firm_id);
CREATE INDEX user_firm_preferences_firm_idx ON user_firm_preferences (firm_id);
CREATE INDEX user_credentials_user_idx ON user_credentials (user_id);
CREATE INDEX user_credentials_profile_idx ON user_credentials (authentication_profile_id);
CREATE INDEX role_permissions_permission_idx ON role_permissions (permission_id);
CREATE INDEX user_role_assignments_role_idx ON user_role_assignments (role_id);
CREATE INDEX user_role_assignments_institution_idx ON user_role_assignments (institution_id);
CREATE INDEX user_role_assignments_assigner_idx ON user_role_assignments (assigned_by_user_id);
CREATE INDEX sessions_user_idx ON sessions (user_id);
CREATE INDEX sessions_institution_idx ON sessions (institution_id);
CREATE INDEX sessions_site_idx ON sessions (site_id);
CREATE INDEX sessions_firm_idx ON sessions (firm_id);

CREATE TABLE audit_events (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    event_type TEXT NOT NULL CHECK (btrim(event_type) <> ''),
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    actor_user_id BIGINT REFERENCES users(id),
    target_user_id BIGINT REFERENCES users(id),
    session_id BIGINT REFERENCES sessions(id),
    institution_id BIGINT REFERENCES institutions(id),
    site_id BIGINT REFERENCES sites(id),
    firm_id BIGINT REFERENCES firms(id),
    outcome TEXT NOT NULL CHECK (outcome IN ('success', 'failure', 'denied')),
    reason_code TEXT NOT NULL CHECK (btrim(reason_code) <> ''),
    correlation_id TEXT NOT NULL CHECK (btrim(correlation_id) <> ''),
    source_ip_class TEXT,
    attributes JSONB NOT NULL DEFAULT '{}'::jsonb,
    CHECK (jsonb_typeof(attributes) = 'object')
);

CREATE INDEX audit_events_occurred_at_idx ON audit_events (occurred_at DESC);
CREATE INDEX audit_events_actor_idx ON audit_events (actor_user_id, occurred_at DESC);
CREATE INDEX audit_events_target_idx ON audit_events (target_user_id, occurred_at DESC);
CREATE INDEX audit_events_session_idx ON audit_events (session_id, occurred_at DESC);
CREATE INDEX audit_events_institution_idx ON audit_events (institution_id, occurred_at DESC);
CREATE INDEX audit_events_site_idx ON audit_events (site_id, occurred_at DESC);
CREATE INDEX audit_events_firm_idx ON audit_events (firm_id, occurred_at DESC);
CREATE INDEX audit_events_session_denial_idx
    ON audit_events (session_id, event_type, reason_code, occurred_at DESC)
    WHERE session_id IS NOT NULL AND outcome = 'denied';

CREATE FUNCTION reject_audit_event_mutation() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION 'audit_events is append-only';
END;
$$;

CREATE TRIGGER audit_events_no_update_or_delete
BEFORE UPDATE OR DELETE ON audit_events
FOR EACH ROW EXECUTE FUNCTION reject_audit_event_mutation();

CREATE TRIGGER audit_events_no_truncate
BEFORE TRUNCATE ON audit_events
FOR EACH STATEMENT EXECUTE FUNCTION reject_audit_event_mutation();
