CREATE TABLE development_operative_note_catalogue (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category TEXT NOT NULL CHECK (category IN ('procedure', 'laterality', 'surgeon', 'anaesthetic', 'delivery')),
    code TEXT NOT NULL UNIQUE CHECK (code LIKE 'development\_%'),
    display_name TEXT NOT NULL CHECK (btrim(display_name) <> '' AND char_length(display_name) <= 200),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    display_order INTEGER NOT NULL CHECK (display_order >= 0),
    UNIQUE (category, display_order)
);

INSERT INTO development_operative_note_catalogue (category, code, display_name, display_order) VALUES
('procedure', 'development_cataract_extraction', 'Development cataract extraction', 0),
('procedure', 'development_trabeculectomy', 'Development trabeculectomy', 1),
('laterality', 'development_right_eye', 'Right eye', 0),
('laterality', 'development_left_eye', 'Left eye', 1),
('laterality', 'development_bilateral', 'Both eyes', 2),
('surgeon', 'development_surgeon_a', 'Development surgeon A', 0),
('surgeon', 'development_surgeon_b', 'Development surgeon B', 1),
('anaesthetic', 'development_local_anaesthetic', 'Development local anaesthetic', 0),
('anaesthetic', 'development_general_anaesthetic', 'Development general anaesthetic', 1),
('anaesthetic', 'development_no_anaesthetic', 'Development no anaesthetic', 2),
('delivery', 'development_subtenons', 'Development sub-Tenon', 0),
('delivery', 'development_topical', 'Development topical', 1),
('delivery', 'development_other', 'Development other', 2);
