CREATE TABLE intraocular_pressure_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT NOT NULL UNIQUE CHECK (code ~ '^[a-z][a-z0-9_]{0,63}$'),
    display_name TEXT NOT NULL CHECK (btrim(display_name) <> '' AND char_length(display_name) <= 200),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    display_order INTEGER NOT NULL CHECK (display_order >= 0),
    created_by_user_id BIGINT REFERENCES users(id),
    updated_by_user_id BIGINT REFERENCES users(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CHECK (updated_at >= created_at)
);

CREATE TABLE intraocular_pressure_profile_values (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id BIGINT NOT NULL REFERENCES intraocular_pressure_profiles(id) ON DELETE RESTRICT,
    code TEXT NOT NULL UNIQUE CHECK (code ~ '^[a-z][a-z0-9_]{0,63}$'),
    display_value TEXT NOT NULL CHECK (btrim(display_value) <> '' AND char_length(display_value) <= 200),
    mmhg SMALLINT NOT NULL CHECK (mmhg BETWEEN 0 AND 99),
    selectable BOOLEAN NOT NULL DEFAULT TRUE,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    display_order INTEGER NOT NULL CHECK (display_order >= 0),
    created_by_user_id BIGINT REFERENCES users(id),
    updated_by_user_id BIGINT REFERENCES users(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (profile_id, mmhg),
    CHECK (updated_at >= created_at)
);

CREATE INDEX intraocular_pressure_profiles_active_display_idx
    ON intraocular_pressure_profiles (display_order, code) WHERE active;
CREATE INDEX intraocular_pressure_profile_values_active_profile_display_idx
    ON intraocular_pressure_profile_values (profile_id, display_order, code) WHERE active AND selectable;
