DROP TRIGGER IF EXISTS audit_events_no_update_or_delete ON audit_events;
DROP TRIGGER IF EXISTS audit_events_no_truncate ON audit_events;
DROP FUNCTION IF EXISTS reject_audit_event_mutation();
DROP TABLE IF EXISTS audit_events;
DROP TABLE IF EXISTS sessions;
DROP TABLE IF EXISTS user_role_assignments;
DROP TABLE IF EXISTS role_permissions;
DROP TABLE IF EXISTS roles;
DROP TABLE IF EXISTS permissions;
DROP TABLE IF EXISTS user_credentials;
DROP TABLE IF EXISTS authentication_profiles;
DROP TABLE IF EXISTS user_firm_preferences;
DROP TABLE IF EXISTS user_firm_memberships;
DROP TABLE IF EXISTS user_site_memberships;
DROP TABLE IF EXISTS user_institution_memberships;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS firms;
DROP TABLE IF EXISTS sites;
DROP TABLE IF EXISTS institutions;
DROP TYPE IF EXISTS credential_state;
