services:
  - type: web
    name: libre-eyes-demo
    runtime: docker
    region: frankfurt
    branch: main
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    numInstances: 1
    healthCheckPath: /health/live
    envVars:
      - key: LIBREEYES_ENV
        value: development
      - key: LIBREEYES_HTTP_ADDR
        value: :10000
      - key: LIBREEYES_STATIC_DIR
        value: /app/web
      - key: LIBREEYES_COOKIE_SECURE
        value: "true"
      - key: LIBREEYES_DATABASE_URL
        fromDatabase:
          name: libre-eyes-demo-db
          property: connectionString
      - key: LIBREEYES_CSRF_KEY
        value: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

databases:
  - name: libre-eyes-demo-db
    region: frankfurt
    plan: free
    databaseName: libreeyes
    user: libreeyes
