/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/presentation/branding": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read a published presentation profile or safe defaults */
        get: {
            parameters: {
                query?: {
                    institutionId?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Published profile or embedded fallback */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BrandingProfile"];
                    };
                };
                400: components["responses"]["Problem"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/branding": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read the current institution branding administration state */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Effective, draft, history, and audit state */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BrandingState"];
                    };
                };
                403: components["responses"]["Problem"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/branding/draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Create or replace the current institution branding draft */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["BrandingDraft"];
                };
            };
            responses: {
                /** @description Updated branding state */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BrandingState"];
                    };
                };
                400: components["responses"]["Problem"];
                403: components["responses"]["Problem"];
                409: components["responses"]["Problem"];
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/branding/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Publish the current institution branding draft */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["VersionCommand"];
                };
            };
            responses: {
                /** @description Published branding state */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BrandingState"];
                    };
                };
                403: components["responses"]["Problem"];
                409: components["responses"]["Problem"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/branding/rollback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Republish a superseded profile as a new version */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["VersionCommand"] & {
                        /** Format: int64 */
                        targetProfileVersion: number;
                    };
                };
            };
            responses: {
                /** @description Rolled-back branding state */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BrandingState"];
                    };
                };
                403: components["responses"]["Problem"];
                404: components["responses"]["Problem"];
                409: components["responses"]["Problem"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        BrandingColors: {
            primary: components["schemas"]["HexColor"];
            primaryHover: components["schemas"]["HexColor"];
            selectedSurface: components["schemas"]["HexColor"];
            focus: components["schemas"]["HexColor"];
        };
        HexColor: string;
        BrandingProfile: {
            /** Format: int64 */
            institutionId?: number;
            /** Format: int64 */
            profileVersion: number;
            /** Format: int64 */
            rowVersion: number;
            /** @enum {string} */
            status: "default" | "draft" | "published" | "superseded";
            /** @enum {string} */
            source: "default" | "draft" | "published";
            organizationName: string;
            shortName: string;
            browserTitle: string;
            colors: components["schemas"]["BrandingColors"];
        };
        BrandingDraft: {
            organizationName: string;
            shortName: string;
            browserTitle: string;
            colors: components["schemas"]["BrandingColors"];
            /** Format: int64 */
            expectedVersion: number;
        };
        VersionCommand: {
            /** Format: int64 */
            expectedVersion: number;
        };
        BrandingSummary: {
            /** Format: int64 */
            profileVersion: number;
            /** Format: int64 */
            rowVersion: number;
            /** @enum {string} */
            status: "draft" | "published" | "superseded";
            /** Format: date-time */
            updatedAt: string;
            /** Format: date-time */
            publishedAt?: string;
        };
        BrandingAuditEvent: {
            /** @enum {string} */
            command: "branding.draft_saved" | "branding.published" | "branding.rolled_back";
            /** Format: int64 */
            profileVersion: number;
            actorDisplayName: string;
            before: {
                [key: string]: unknown;
            };
            after: {
                [key: string]: unknown;
            };
            correlationId: string;
            /** Format: date-time */
            createdAt: string;
        };
        BrandingState: {
            effective: components["schemas"]["BrandingProfile"];
            published?: components["schemas"]["BrandingProfile"];
            draft?: components["schemas"]["BrandingProfile"];
            history: components["schemas"]["BrandingSummary"][];
            audit: components["schemas"]["BrandingAuditEvent"][];
        };
        Problem: {
            type?: string;
            title: string;
            status: number;
            code: string;
            correlationId?: string;
            fieldErrors?: components["schemas"]["BrandingFieldError"][];
        };
        BrandingFieldError: {
            /** @enum {string} */
            field: "colors.primary" | "colors.primaryHover" | "colors.selectedSurface" | "colors.focus";
            label: string;
            against: string;
            message: string;
            /** Format: double */
            contrastRatio: number;
            /** Format: double */
            minimumContrast: number;
        };
    };
    responses: {
        /** @description RFC 7807-style bounded problem response */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
