/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/patients/{patientId}/episodes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List episodes visible to the current clinical context */
        get: operations["listPatientEpisodes"];
        put?: never;
        /**
         * Create an episode in the server-derived clinical context
         * @description Principal-diagnosis writes are deferred to their own approved contract.
         */
        post: operations["createEpisode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/episodes/{episodeId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read one authorized episode header */
        get: operations["getEpisode"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Change an approved episode lifecycle state
         * @description Requires an expected version. The server derives institution, site, and firm scope from the authenticated context; request bodies cannot select those scopes. Principal-diagnosis writes are deferred to their own approved contract.
         */
        patch: operations["updateEpisode"];
        trace?: never;
    };
    "/episodes/{episodeId}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List authorized event headers for an episode */
        get: operations["listEpisodeEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{eventId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read one authorized event header
         * @description Clinical element payloads are excluded from this increment.
         */
        get: operations["getEventHeader"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/episodes/{episodeId}/event-drafts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Save a clinician-owned, uncommitted event draft */
        post: operations["createEventDraft"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/event-drafts/{draftId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recover an authorized unexpired draft */
        get: operations["getEventDraft"];
        put?: never;
        post?: never;
        /** Audited soft deletion of an owned draft */
        delete: operations["abandonEventDraft"];
        options?: never;
        head?: never;
        /** Update an owned draft using optimistic concurrency */
        patch: operations["updateEventDraft"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        EpisodeCreateRequest: {
            /** @enum {string} */
            status: "open" | "active";
        };
        EpisodeUpdateRequest: {
            expectedVersion: number;
            /** @enum {string} */
            lifecycleAction?: "activate" | "close" | "reopen";
            reopenReason?: string;
        } & (unknown & unknown);
        Episode: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            patientId: string;
            /** @enum {string} */
            status: "open" | "active" | "closed";
            startedAt: string | null;
            endedAt: string | null;
            supportServices: boolean;
            changeTracker: boolean;
            version: number;
        };
        EpisodePage: {
            items: components["schemas"]["Episode"][];
            nextCursor: string | null;
        };
        EventHeader: {
            /** Format: uuid */
            id: string;
            /** @description Null only for retained imported orphan events. Current list routes never return orphan events. */
            episodeId: string | null;
            eventTypeCode: string;
            /** Format: date-time */
            occurredAt: string;
            /** @constant */
            status: "current";
            version: number;
        };
        EventPage: {
            items: components["schemas"]["EventHeader"][];
            nextCursor: string | null;
        };
        DraftCreateRequest: {
            eventTypeCode: string;
            /** @description Existing authorized event being drafted for update. It is immutable after draft creation and must belong to the path episode. */
            targetEventId?: string | null;
            /**
             * @description An update intent requires targetEventId; a create intent forbids it.
             * @default create
             * @enum {string}
             */
            intent: "create" | "update";
            /** @enum {string} */
            mode: "autosave" | "manual";
            schemaVersion: number;
            /** @description Module-owned draft-only JSON. The server accepts it only for an approved event-type/schema-version registry entry, enforces a 64 KiB decoded-body limit and depth/key limits, and never treats it as a committed clinical element. */
            payload: Record<string, never>;
        } & (unknown & unknown);
        DraftUpdateRequest: {
            expectedVersion: number;
            schemaVersion: number;
            /** @description Module-owned draft-only JSON. The server enforces a 64 KiB decoded body limit, a maximum nesting depth of 16, and 2,000 object keys before persistence. */
            payload: Record<string, never>;
        };
        EventDraft: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            episodeId: string;
            eventTypeCode: string;
            targetEventId?: string | null;
            /** @enum {string} */
            intent: "create" | "update";
            /** @enum {string} */
            mode: "autosave" | "manual";
            schemaVersion: number;
            payload: Record<string, never>;
            version: number;
            /** Format: date-time */
            expiresAt: string;
            newerCommittedEdits?: boolean;
        };
        Problem: {
            /** Format: uri-reference */
            type: string;
            /** @description Must not include request content, field values, or clinical payload fragments. */
            title: string;
            status: number;
            /** @description Stable generic error code; never includes request content or clinical payload fragments. */
            code?: string;
            correlationId: string;
        };
    };
    responses: {
        /** @description Non-cacheable episode representation */
        EpisodeResponse: {
            headers: {
                "Cache-Control"?: "no-store";
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Episode"];
            };
        };
        /** @description Non-cacheable authorized episode headers */
        EpisodeList: {
            headers: {
                "Cache-Control"?: "no-store";
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["EpisodePage"];
            };
        };
        /** @description Non-cacheable event-header representation */
        EventResponse: {
            headers: {
                "Cache-Control"?: "no-store";
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["EventHeader"];
            };
        };
        /** @description Non-cacheable authorized event headers */
        EventList: {
            headers: {
                "Cache-Control"?: "no-store";
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["EventPage"];
            };
        };
        /** @description Non-cacheable owned draft representation */
        DraftResponse: {
            headers: {
                "Cache-Control"?: "no-store";
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["EventDraft"];
            };
        };
        /** @description Invalid request; response does not echo clinical payloads */
        BadRequest: {
            headers: {
                "Cache-Control"?: "no-store";
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Missing, expired, or revoked session */
        Unauthenticated: {
            headers: {
                "Cache-Control"?: "no-store";
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Context, CSRF, or resource authorization failed without existence disclosure */
        Forbidden: {
            headers: {
                "Cache-Control"?: "no-store";
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Authorized resource was not found */
        NotFound: {
            headers: {
                "Cache-Control"?: "no-store";
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Version mismatch or tied pathway candidates; no partial write occurred */
        Conflict: {
            headers: {
                "Cache-Control"?: "no-store";
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        CsrfToken: string;
        PatientId: string;
        EpisodeId: string;
        EventId: string;
        DraftId: string;
        /** @description Required even though the abandon operation has no request body. The service validates this query parameter and the CSRF header before any draft state change. */
        ExpectedVersion: number;
        /** @description Required only when a same-institution read exceeds ordinary site/firm scope. The server validates the override permission and records the reason in a minimal read audit event. */
        AccessOverrideReason: string;
        PageLimit: number;
        PageCursor: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listPatientEpisodes: {
        parameters: {
            query?: {
                limit?: components["parameters"]["PageLimit"];
                cursor?: components["parameters"]["PageCursor"];
            };
            header: {
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path: {
                patientId: components["parameters"]["PatientId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["EpisodeList"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
        };
    };
    createEpisode: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path: {
                patientId: components["parameters"]["PatientId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EpisodeCreateRequest"];
            };
        };
        responses: {
            201: components["responses"]["EpisodeResponse"];
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    getEpisode: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
                /** @description Required only when a same-institution read exceeds ordinary site/firm scope. The server validates the override permission and records the reason in a minimal read audit event. */
                "X-Access-Override-Reason"?: components["parameters"]["AccessOverrideReason"];
            };
            path: {
                episodeId: components["parameters"]["EpisodeId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["EpisodeResponse"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
        };
    };
    updateEpisode: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path: {
                episodeId: components["parameters"]["EpisodeId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EpisodeUpdateRequest"];
            };
        };
        responses: {
            200: components["responses"]["EpisodeResponse"];
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    listEpisodeEvents: {
        parameters: {
            query?: {
                limit?: components["parameters"]["PageLimit"];
                cursor?: components["parameters"]["PageCursor"];
            };
            header?: {
                /** @description Required only when a same-institution read exceeds ordinary site/firm scope. The server validates the override permission and records the reason in a minimal read audit event. */
                "X-Access-Override-Reason"?: components["parameters"]["AccessOverrideReason"];
            };
            path: {
                episodeId: components["parameters"]["EpisodeId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["EventList"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    getEventHeader: {
        parameters: {
            query?: never;
            header?: {
                /** @description Required only when a same-institution read exceeds ordinary site/firm scope. The server validates the override permission and records the reason in a minimal read audit event. */
                "X-Access-Override-Reason"?: components["parameters"]["AccessOverrideReason"];
            };
            path: {
                eventId: components["parameters"]["EventId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["EventResponse"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    createEventDraft: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path: {
                episodeId: components["parameters"]["EpisodeId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DraftCreateRequest"];
            };
        };
        responses: {
            201: components["responses"]["DraftResponse"];
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    getEventDraft: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                draftId: components["parameters"]["DraftId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["DraftResponse"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    abandonEventDraft: {
        parameters: {
            query: {
                /** @description Required even though the abandon operation has no request body. The service validates this query parameter and the CSRF header before any draft state change. */
                expectedVersion: components["parameters"]["ExpectedVersion"];
            };
            header: {
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path: {
                draftId: components["parameters"]["DraftId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Draft abandoned */
            204: {
                headers: {
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    updateEventDraft: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path: {
                draftId: components["parameters"]["DraftId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DraftUpdateRequest"];
            };
        };
        responses: {
            200: components["responses"]["DraftResponse"];
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
}
