/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/patients/recent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List an explicitly requested capped set of recent patients
         * @description Institution/site-scoped minimum-disclosure view. This endpoint is opt-in, capped at 50 records, and audited.
         */
        get: operations["listRecentPatients"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/patients/searches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Search current-institution patients using approved structured criteria
         * @description Requires patient.search and a validated institution, site, and firm context. Search criteria are carried in the JSON body so names, dates, and identifiers do not enter URL logs or browser history. The operation is read-only except for its required append-only audit event.
         */
        post: operations["searchPatients"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/patients/duplicate-candidates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Find exact-only duplicate candidates without changing patient state
         * @description Requires patient.duplicate_check and a validated institution, site, and firm context. The response is explicitly incomplete: no candidates does not prove that a duplicate does not exist locally or in another institution. Only current-institution patients can be disclosed, and this operation never authorizes automatic merge or patient creation.
         */
        post: operations["findPatientDuplicateCandidates"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Format: uuid
         * @description Non-sequential public patient identifier; not a clinical identifier
         */
        PatientPublicID: string;
        /** @description Decimal identifier for approved configuration records */
        DatabaseIdentifier: string;
        /**
         * @description Administrative gender code used by the approved demographic search
         * @enum {string}
         */
        GenderCode: "female" | "male" | "other" | "unknown";
        PatientSearchRequest: {
            criteria: components["schemas"]["PatientSearchCriteria"];
            /** @default 25 */
            limit: number;
            /** @description Confidential, integrity-protected opaque cursor. It contains no recoverable plaintext patient/search data and is bound to the actor/session, institution/site/firm, criteria digest, page limit, ordering and normalization versions, and expiry. */
            cursor?: string | null;
        };
        PatientSearchCriteria: components["schemas"]["IdentifierSearchCriteria"] | components["schemas"]["DemographicSearchCriteria"];
        IdentifierSearchCriteria: {
            /** @constant */
            kind: "identifier";
            identifierTypeId: components["schemas"]["DatabaseIdentifier"];
            /** @description Presentation input. The server applies only the explicitly selected type's approved normalization and validation rule. */
            value: string;
        };
        DemographicSearchCriteria: {
            /** @constant */
            kind: "demographic";
            familyName: string;
            givenName?: string;
            /** Format: date */
            dateOfBirth: string;
            gender: components["schemas"]["GenderCode"];
        };
        PatientSearchPage: {
            items: components["schemas"]["PatientSearchResult"][];
            page: components["schemas"]["CursorPage"];
        };
        CursorPage: {
            /** @constant */
            hasMore: true;
            nextCursor: string;
        } | {
            /** @constant */
            hasMore: false;
            nextCursor: null;
        };
        PatientSearchResult: {
            patientId: components["schemas"]["PatientPublicID"];
            fullName: string | null;
            givenName: string | null;
            familyName: string | null;
            /** Format: date */
            dateOfBirth: string;
            gender: components["schemas"]["GenderCode"];
            primaryIdentifier: components["schemas"]["DisplayedPatientIdentifier"] | null;
            deceased: boolean;
            dateOfDeath: string | null;
        };
        DisplayedPatientIdentifier: {
            typeId: components["schemas"]["DatabaseIdentifier"];
            label: string;
            /** @description Approved display form of the active identifier */
            value: string;
        };
        DuplicateCandidateRequest: {
            criteria: components["schemas"]["DuplicateCriteria"];
        };
        DuplicateCriteria: components["schemas"]["IdentifierDuplicateCriteria"] | components["schemas"]["DemographicDuplicateCriteria"];
        IdentifierDuplicateCriteria: components["schemas"]["IdentifierSearchCriteria"];
        DemographicDuplicateCriteria: {
            /** @constant */
            kind: "demographic";
            givenName: string;
            familyName: string;
            /** Format: date */
            dateOfBirth: string;
        };
        DuplicateCandidateResponse: {
            /**
             * @description Only exact configured-identifier or exact normalized-demographic matching ran
             * @constant
             */
            coverage: "exact_only";
            /**
             * @description Patients in other institutions are neither queried for disclosure nor returned
             * @constant
             */
            populationCoverage: "current_institution_only";
            /** @constant */
            complete: false;
            /** @constant */
            noCandidatesDoesNotExcludeDuplicate: true;
            /** @description True only when the exact active identifier belongs to a disclosed current-institution candidate. A future write still performs the authoritative database uniqueness check. */
            hardConflict: boolean;
            /** @description True when more exact candidates exist than the bounded response contains */
            truncated: boolean;
            /** @description At most 100 current-institution exact candidates */
            candidates: components["schemas"]["DuplicateCandidate"][];
        };
        DuplicateCandidate: {
            /** @enum {string} */
            reason: "exact_identifier" | "exact_demographics";
            patient: components["schemas"]["PatientSearchResult"];
        };
        Problem: {
            /** Format: uri-reference */
            type: string;
            /** @description Generic title that never interpolates search criteria or patient data */
            title: string;
            status: number;
            /** @description Optional generic explanation. It never echoes raw or normalized names, dates, gender criteria, clinical identifiers, candidate identities, session data, or response content. */
            detail?: string;
            /** @description Stable machine-readable error code without patient-existence detail */
            code: string;
            correlationId: string;
        } & {
            [key: string]: unknown;
        };
    };
    responses: {
        /** @description Invalid request shape, field, date, cursor, or identifier configuration */
        BadRequest: {
            headers: {
                "Cache-Control"?: "no-store";
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Session is missing, expired, or revoked */
        Unauthenticated: {
            headers: {
                "Cache-Control"?: "no-store";
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description CSRF, context, or operation authorization failed. The response contains no patient-existence information. */
        Forbidden: {
            headers: {
                "Cache-Control"?: "no-store";
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Decoded request body exceeds 8 KiB */
        PayloadTooLarge: {
            headers: {
                "Cache-Control"?: "no-store";
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Authenticated-principal search rate limit exceeded */
        TooManyRequests: {
            headers: {
                "Retry-After"?: number;
                "Cache-Control"?: "no-store";
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Search cannot safely disclose results, including when its required audit event cannot be durably written. */
        SearchUnavailable: {
            headers: {
                "Cache-Control"?: "no-store";
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Server search deadline expired; no partial result is returned */
        SearchTimeout: {
            headers: {
                "Cache-Control"?: "no-store";
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        /** @description Session-bound anti-CSRF token from the current session representation */
        CsrfToken: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listRecentPatients: {
        parameters: {
            query?: {
                limit?: number;
            };
            header: {
                /** @description Session-bound anti-CSRF token from the current session representation */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recent patient result page */
            200: {
                headers: {
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatientSearchPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
        };
    };
    searchPatients: {
        parameters: {
            query?: never;
            header: {
                /** @description Session-bound anti-CSRF token from the current session representation */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path?: never;
            cookie?: never;
        };
        /** @description Maximum decoded request body is 8 KiB. */
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatientSearchRequest"];
            };
        };
        responses: {
            /** @description Stable bounded result page. An absent patient and a patient outside the current institution both produce an empty page. */
            200: {
                headers: {
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatientSearchPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            413: components["responses"]["PayloadTooLarge"];
            429: components["responses"]["TooManyRequests"];
            503: components["responses"]["SearchUnavailable"];
            504: components["responses"]["SearchTimeout"];
        };
    };
    findPatientDuplicateCandidates: {
        parameters: {
            query?: never;
            header: {
                /** @description Session-bound anti-CSRF token from the current session representation */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path?: never;
            cookie?: never;
        };
        /** @description Maximum decoded request body is 8 KiB. */
        requestBody: {
            content: {
                "application/json": components["schemas"]["DuplicateCandidateRequest"];
            };
        };
        responses: {
            /** @description Exact-only candidate result, durably audited before disclosure */
            200: {
                headers: {
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DuplicateCandidateResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            413: components["responses"]["PayloadTooLarge"];
            429: components["responses"]["TooManyRequests"];
            503: components["responses"]["SearchUnavailable"];
            504: components["responses"]["SearchTimeout"];
        };
    };
}
