/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login-options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List safe institution and site choices for local login */
        get: operations["listLoginOptions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Authenticate a local user and establish a complete context */
        post: operations["createSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read the current authenticated user and complete context */
        get: operations["getCurrentSession"];
        put?: never;
        post?: never;
        /** Revoke the current session */
        delete: operations["deleteCurrentSession"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/session/context": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Replace the current session's institution, site, and firm context */
        put: operations["replaceCurrentContext"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Decimal representation of a database identifier */
        Identifier: string;
        LoginRequest: {
            username: string;
            password: string;
            institutionId: components["schemas"]["Identifier"];
            siteId: components["schemas"]["Identifier"];
            /** @description Optional requested firm. If omitted, the server may use the single deterministic authorized default; it never trusts a client default. */
            firmId?: components["schemas"]["Identifier"];
        };
        ReplaceContextRequest: {
            institutionId: components["schemas"]["Identifier"];
            siteId: components["schemas"]["Identifier"];
            firmId: components["schemas"]["Identifier"];
        };
        LoginOptions: {
            institutions: components["schemas"]["InstitutionLoginOption"][];
        };
        InstitutionLoginOption: {
            id: components["schemas"]["Identifier"];
            name: string;
            sites: components["schemas"]["NamedReference"][];
        };
        NamedReference: {
            id: components["schemas"]["Identifier"];
            name: string;
        };
        SessionRepresentation: {
            user: components["schemas"]["AuthenticatedUser"];
            context: components["schemas"]["UserContext"];
            permissions: string[];
            /** @description Anti-CSRF value, not the session credential */
            csrfToken: string;
            /** Format: date-time */
            idleExpiresAt: string;
            /** Format: date-time */
            absoluteExpiresAt: string;
            /** Format: int64 */
            contextVersion: number;
        };
        AuthenticatedUser: {
            id: components["schemas"]["Identifier"];
            displayName: string;
        };
        UserContext: {
            institution: components["schemas"]["NamedReference"];
            site: components["schemas"]["NamedReference"];
            firm: components["schemas"]["NamedReference"];
        };
        Problem: {
            /** Format: uri-reference */
            type: string;
            title: string;
            status: number;
            detail?: string;
            /** @description Stable machine-readable error code */
            code: string;
            correlationId: string;
        } & {
            [key: string]: unknown;
        };
    };
    responses: {
        /** @description Invalid request syntax or fields */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Session is missing, expired, or revoked */
        Unauthenticated: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description CSRF validation failed */
        CsrfRejected: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Request rate limit exceeded */
        TooManyRequests: {
            headers: {
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        /** @description Session-bound anti-CSRF token obtained from the session representation */
        CsrfToken: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listLoginOptions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Active login choices containing no user-specific data */
            200: {
                headers: {
                    "Cache-Control"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginOptions"];
                };
            };
            429: components["responses"]["TooManyRequests"];
        };
    };
    createSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Authenticated session created */
            200: {
                headers: {
                    /** @description Opaque libreeyes_session cookie with Secure, HttpOnly, SameSite=Lax, and Path=/ attributes. */
                    "Set-Cookie"?: string;
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionRepresentation"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description Generic authentication failure. The response never reveals whether username, password, account state, permission, hash state, context access, or context resolution caused the failure. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            429: components["responses"]["TooManyRequests"];
        };
    };
    getCurrentSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current active session */
            200: {
                headers: {
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionRepresentation"];
                };
            };
            401: components["responses"]["Unauthenticated"];
        };
    };
    deleteCurrentSession: {
        parameters: {
            query?: never;
            header: {
                /** @description Session-bound anti-CSRF token obtained from the session representation */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current session revoked; the session cookie is expired */
            204: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["CsrfRejected"];
        };
    };
    replaceCurrentContext: {
        parameters: {
            query?: never;
            header: {
                /** @description Session-bound anti-CSRF token obtained from the session representation */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
                /** @description Quoted current context version returned by the API */
                "If-Match": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReplaceContextRequest"];
            };
        };
        responses: {
            /** @description Context replaced and audited */
            200: {
                headers: {
                    /** @description Quoted new context version */
                    ETag?: string;
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionRepresentation"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
            /** @description CSRF check failed, permission denied, or context inaccessible */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Context version conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
}
