/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/development/theatre-booking/board": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getDevelopmentTheatreBookingBoard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/development/theatre-booking/requests/{requestId}/schedule": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                requestId: components["parameters"]["RequestId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["scheduleDevelopmentTheatreBookingRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/development/theatre-booking/requests/{requestId}/reschedule": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                requestId: components["parameters"]["RequestId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["rescheduleDevelopmentTheatreBookingRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/development/theatre-booking/requests/{requestId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                requestId: components["parameters"]["RequestId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["cancelDevelopmentTheatreBookingRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Board: {
            /** @constant */
            developmentOnly: true;
            /** Format: date */
            sessionDate: string;
            theatreSessions: components["schemas"]["TheatreSession"][];
            bookingRequests: components["schemas"]["BookingRequest"][];
            /** @description Derived, read-only summary of synthetic scheduled requests. */
            whiteboard: components["schemas"]["WhiteboardEntry"][];
        };
        TheatreSession: {
            /** Format: uuid */
            id: string;
            syntheticRoomLabel: string;
            /** Format: date-time */
            startsAt: string;
            /** Format: date-time */
            endsAt: string;
            capacityMinutes: number;
            allocatedMinutes: number;
            version: number;
        };
        BookingRequest: {
            /** Format: uuid */
            id: string;
            syntheticLabel: string;
            requestedDurationMinutes: number;
            /** @enum {string} */
            status: "waiting" | "scheduled" | "cancelled";
            /** Format: uuid */
            assignedSessionId: string | null;
            version: number;
        };
        WhiteboardEntry: {
            /** Format: uuid */
            sessionId: string;
            syntheticRoomLabel: string;
            entries: {
                /** Format: uuid */
                requestId: string;
                syntheticLabel: string;
                requestedDurationMinutes: number;
            }[];
        };
        Problem: {
            /** Format: uri-reference */
            type: string;
            title: string;
            status: number;
            code: string;
            correlationId: string;
        };
        ConflictProblem: components["schemas"]["Problem"] & {
            /** @enum {string} */
            code?: "stale_version" | "invalid_state" | "insufficient_capacity";
        };
    };
    responses: {
        /** @description Updated synthetic request. */
        UpdatedBookingRequest: {
            headers: {
                "Cache-Control"?: "no-store";
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["BookingRequest"];
            };
        };
        /** @description Invalid command or unsupported development filter. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description No valid session. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description The current actor lacks the development theatre-booking permission. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Synthetic resource is absent or outside current context. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Stale version, invalid transition, or insufficient session capacity. No state change occurred. */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ConflictProblem"];
            };
        };
    };
    parameters: {
        /** @description Session-bound CSRF token obtained from the authenticated session representation. */
        CsrfToken: string;
        RequestId: string;
    };
    requestBodies: {
        SessionAssignmentCommand: {
            content: {
                "application/json": {
                    expectedVersion: number;
                    /** Format: uuid */
                    targetSessionId: string;
                };
            };
        };
    };
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getDevelopmentTheatreBookingBoard: {
        parameters: {
            query?: {
                /** @description Optional ISO calendar date. The server rejects values outside the development fixture's permitted range. */
                sessionDate?: string;
                theatreRoomId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current-context synthetic theatre board and derived whiteboard. */
            200: {
                headers: {
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Board"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    scheduleDevelopmentTheatreBookingRequest: {
        parameters: {
            query?: never;
            header: {
                /** @description Session-bound CSRF token obtained from the authenticated session representation. */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path: {
                requestId: components["parameters"]["RequestId"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["SessionAssignmentCommand"];
        responses: {
            200: components["responses"]["UpdatedBookingRequest"];
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    rescheduleDevelopmentTheatreBookingRequest: {
        parameters: {
            query?: never;
            header: {
                /** @description Session-bound CSRF token obtained from the authenticated session representation. */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path: {
                requestId: components["parameters"]["RequestId"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["SessionAssignmentCommand"];
        responses: {
            200: components["responses"]["UpdatedBookingRequest"];
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    cancelDevelopmentTheatreBookingRequest: {
        parameters: {
            query?: never;
            header: {
                /** @description Session-bound CSRF token obtained from the authenticated session representation. */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path: {
                requestId: components["parameters"]["RequestId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    expectedVersion: number;
                };
            };
        };
        responses: {
            200: components["responses"]["UpdatedBookingRequest"];
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
}
