/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/development/clinic-flow/tickets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listDevelopmentClinicFlowTickets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/development/clinic-flow/tickets/{ticketId}/arrive": components["pathItems"]["TicketCommand"];
    "/api/v1/development/clinic-flow/tickets/{ticketId}/claim": components["pathItems"]["TicketCommand"];
    "/api/v1/development/clinic-flow/tickets/{ticketId}/release": components["pathItems"]["TicketCommand"];
    "/api/v1/development/clinic-flow/tickets/{ticketId}/complete": components["pathItems"]["TicketCommand"];
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Ticket: {
            /** Format: uuid */
            id: string;
            syntheticPatientLabel: string;
            /** @enum {string} */
            status: "waiting" | "arrived" | "in_progress" | "completed";
            assigneeDisplayName?: string | null;
            version: number;
        };
    };
    responses: never;
    parameters: {
        /** @description Session-bound token obtained from the authenticated session representation. */
        CsrfToken: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: {
        TicketCommand: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    ticketId: string;
                };
                cookie?: never;
            };
            get?: never;
            put?: never;
            post: {
                parameters: {
                    query?: never;
                    header: {
                        /** @description Session-bound token obtained from the authenticated session representation. */
                        "X-CSRF-Token": components["parameters"]["CsrfToken"];
                    };
                    path: {
                        ticketId: string;
                    };
                    cookie?: never;
                };
                requestBody: {
                    content: {
                        "application/json": {
                            expectedVersion: number;
                        };
                    };
                };
                responses: {
                    /** @description Updated synthetic ticket */
                    200: {
                        headers: {
                            [name: string]: unknown;
                        };
                        content: {
                            "application/json": components["schemas"]["Ticket"];
                        };
                    };
                    /** @description No valid session */
                    401: {
                        headers: {
                            [name: string]: unknown;
                        };
                        content?: never;
                    };
                    /** @description Ticket is not visible or mutable in the current context */
                    404: {
                        headers: {
                            [name: string]: unknown;
                        };
                        content?: never;
                    };
                    /** @description Stale version or invalid transition; no state change */
                    409: {
                        headers: {
                            [name: string]: unknown;
                        };
                        content?: never;
                    };
                };
            };
            delete?: never;
            options?: never;
            head?: never;
            patch?: never;
            trace?: never;
        };
    };
}
export type $defs = Record<string, never>;
export interface operations {
    listDevelopmentClinicFlowTickets: {
        parameters: {
            query?: never;
            header: {
                /** @description Session-bound token obtained from the authenticated session representation. */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current-context synthetic tickets */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Ticket"][];
                    };
                };
            };
        };
    };
}
