import { Save, ScanLine } from 'lucide-react'
import { useEffect, useRef, useState } from 'react'
import { useMutation } from '@tanstack/react-query'
import type { FormEvent } from 'react'
import { episodesAPI, type BiometryDemoDraftPayload, type BiometryDemoEye } from '../../api/client'
import { describeDraftSaveError } from './draftError'

const blankEye = (): BiometryDemoEye => ({ axialLength: '23.50', r1: '7.80', r2: '7.70', r1Axis: 90, r2Axis: 0, acd: '3.20', wtw: '11.80' })
function EyeFields({ label, value, onChange }: { label: string; value: BiometryDemoEye; onChange: (next: BiometryDemoEye) => void }) {
  const field = (name: keyof BiometryDemoEye, title: string, numeric = false) => <label><span>{title}</span><input type={numeric ? 'number' : 'text'} step={numeric ? 1 : 0.01} value={value[name]} onChange={e => onChange({ ...value, [name]: numeric ? Number(e.target.value) : e.target.value })} /></label>
  return <fieldset><legend>{label}</legend>{field('axialLength', 'Axial length (mm)')}{field('r1', 'Keratometry R1 (mm)')}{field('r2', 'Keratometry R2 (mm)')}{field('r1Axis', 'R1 axis (degrees)', true)}{field('r2Axis', 'R2 axis (degrees)', true)}{field('acd', 'ACD (mm)')}{field('wtw', 'WTW (mm)')}</fieldset>
}
export function BiometryDraftDemo({ csrfToken, episodeId }: { csrfToken: string; episodeId: string }) {
  const [right, setRight] = useState<BiometryDemoEye | null>(blankEye()); const [left, setLeft] = useState<BiometryDemoEye | null>(blankEye()); const [device, setDevice] = useState<BiometryDemoDraftPayload['deviceCode']>('demo_manual'); const [lens, setLens] = useState<BiometryDemoDraftPayload['lensCode']>('demo_none'); const [date, setDate] = useState(new Date().toISOString().slice(0, 10)); const [comment, setComment] = useState(''); const alertRef = useRef<HTMLParagraphElement>(null)
  const save = useMutation({ mutationFn: (payload: BiometryDemoDraftPayload) => episodesAPI.createBiometryDemoDraft(episodeId, csrfToken, payload) }); useEffect(() => { if (save.isError) alertRef.current?.focus() }, [save.isError])
  function submit(event: FormEvent) { event.preventDefault(); save.reset(); save.mutate({ recordMode: 'demo_biometry', profileCode: 'demo_biometry_v1', deviceCode: device, lensCode: lens, measurementDate: date, rightEye: right, leftEye: left, comment }) }
  const failure = save.isError ? describeDraftSaveError(save.error, 'demo biometry draft') : ''
  return <section className="examination-draft-demo" aria-labelledby={`biometry-demo-${episodeId}`}><div className="examination-draft-demo-heading"><div><p>Demo</p><h3 id={`biometry-demo-${episodeId}`}>Biometry draft</h3></div><ScanLine size={18} aria-hidden="true" /></div><p className="examination-draft-demo-note">Synthetic measurements and an illustrative lens label only. No device import, IOL calculation, clinical interpretation, or clinical record is created.</p><form className="examination-draft-demo-form" onSubmit={submit}><div className="examination-draft-demo-grid"><EyeFields label="Right eye" value={right ?? blankEye()} onChange={setRight} /><EyeFields label="Left eye" value={left ?? blankEye()} onChange={setLeft} /></div><label><span>Demo device</span><select value={device} onChange={e => setDevice(e.target.value as typeof device)}><option value="demo_manual">Demo manual</option><option value="demo_iolmaster">Demo IOLMaster</option></select></label><label><span>Illustrative lens label</span><select value={lens} onChange={e => setLens(e.target.value as typeof lens)}><option value="demo_none">No lens selected</option><option value="demo_ma60ac">Demo MA60AC</option><option value="demo_sn60wf">Demo SN60WF</option><option value="demo_sa60at">Demo SA60AT</option><option value="demo_mta3uo">Demo MTA3UO</option></select></label><label><span>Measurement date</span><input type="date" value={date} onChange={e => setDate(e.target.value)} /></label><label><span>Demo comment</span><textarea maxLength={2000} rows={2} value={comment} onChange={e => setComment(e.target.value)} /></label>{failure && <p className="inline-error" role="alert" tabIndex={-1} ref={alertRef}>{failure}</p>}{save.isSuccess && <p className="inline-success" role="status">Demo biometry draft saved. It remains uncommitted.</p>}<button className="primary-button" type="submit" disabled={save.isPending}><Save size={16} aria-hidden="true" />{save.isPending ? 'Saving draft…' : 'Save demo draft'}</button></form></section>
}
