import { Save, Syringe } from 'lucide-react'
import { useMutation } from '@tanstack/react-query'
import { useState, type FormEvent } from 'react'
import { episodesAPI, type IntravitrealInjectionDemoDraftPayload, type IntravitrealInjectionDemoEye } from '../../api/client'
import { describeDraftSaveError } from './draftError'

const eye = (): IntravitrealInjectionDemoEye => ({ drugCode: 'demo_drug_a', siteCode: 'demo_site_superotemporal', anaestheticCode: 'demo_anaesthetic_topical', injectionNumber: 1, plannedDate: new Date().toISOString().slice(0, 10), postCheck: 'demo_not_recorded' })
export function IntravitrealInjectionDraftDemo({ csrfToken, episodeId }: { csrfToken: string; episodeId: string }) {
  const [eyeMode, setEyeMode] = useState<'both' | 'right' | 'left'>('both'); const [right, setRight] = useState(eye()); const [left, setLeft] = useState(eye()); const [note, setNote] = useState('')
  const save = useMutation({ mutationFn: (payload: IntravitrealInjectionDemoDraftPayload) => episodesAPI.createIntravitrealInjectionDemoDraft(episodeId, csrfToken, payload) })
  function submit(event: FormEvent) { event.preventDefault(); save.reset(); save.mutate({ recordMode: 'demo_intravitreal_injection', profileCode: 'demo_intravitreal_injection_v1', eyeMode, rightEye: eyeMode === 'left' ? null : right, leftEye: eyeMode === 'right' ? null : left, note }) }
  const failure = save.isError ? describeDraftSaveError(save.error, 'demo intravitreal injection draft') : ''
  const fields = (label: string, value: IntravitrealInjectionDemoEye, set: (v: IntravitrealInjectionDemoEye) => void) => <fieldset><legend>{label}</legend><label><span>Demo drug</span><select value={value.drugCode} onChange={e => set({ ...value, drugCode: e.target.value })}><option value="demo_drug_a">Demo anti-VEGF A</option><option value="demo_drug_b">Demo anti-VEGF B</option></select></label><label><span>Demo site</span><select value={value.siteCode} onChange={e => set({ ...value, siteCode: e.target.value })}><option value="demo_site_superotemporal">Demo superotemporal</option><option value="demo_site_inferotemporal">Demo inferotemporal</option></select></label><label><span>Demo anaesthetic</span><select value={value.anaestheticCode} onChange={e => set({ ...value, anaestheticCode: e.target.value })}><option value="demo_anaesthetic_topical">Demo topical</option><option value="demo_anaesthetic_none">Demo none</option></select></label><label><span>Injection number</span><input type="number" min="1" max="10" value={value.injectionNumber} onChange={e => set({ ...value, injectionNumber: Number(e.target.value) })} /></label><label><span>Demo planned date</span><input type="date" value={value.plannedDate} onChange={e => set({ ...value, plannedDate: e.target.value })} /></label><label><span>Demo post-check</span><select value={value.postCheck} onChange={e => set({ ...value, postCheck: e.target.value as IntravitrealInjectionDemoEye['postCheck'] })}><option value="demo_not_recorded">Not recorded</option><option value="demo_clear">Demo clear</option><option value="demo_review">Demo review</option></select></label></fieldset>
  return <section className="examination-draft-demo" aria-labelledby={`intravitreal-demo-${episodeId}`}><div className="examination-draft-demo-heading"><div><p>Demo</p><h3 id={`intravitreal-demo-${episodeId}`}>Intravitreal injection draft</h3></div><Syringe size={18} aria-hidden="true" /></div><p className="examination-draft-demo-note">Synthetic labels only. This does not prescribe, administer, check allergies, create a clinical record, or book treatment.</p><form className="examination-draft-demo-form" onSubmit={submit}><label><span>Eyes recorded</span><select value={eyeMode} onChange={e => setEyeMode(e.target.value as typeof eyeMode)}><option value="both">Both eyes</option><option value="right">Right eye</option><option value="left">Left eye</option></select></label><div className="examination-draft-demo-grid">{eyeMode !== 'left' && fields('Right eye', right, setRight)}{eyeMode !== 'right' && fields('Left eye', left, setLeft)}</div><label><span>Demo note</span><textarea maxLength={1000} rows={2} value={note} onChange={e => setNote(e.target.value)} /></label>{failure && <p className="inline-error" role="alert">{failure}</p>}{save.isSuccess && <p className="inline-success" role="status">Demo intravitreal injection draft saved. It remains uncommitted.</p>}<button className="primary-button" type="submit" disabled={save.isPending}><Save size={16} aria-hidden="true" />{save.isPending ? 'Saving draft…' : 'Save demo draft'}</button></form></section>
}
