import { Gauge, Plus, Save, Trash2 } from 'lucide-react'
import { useMutation } from '@tanstack/react-query'
import { useState } from 'react'
import { episodesAPI, type IOPPhasingDemoDraftPayload, type IOPPhasingDemoEye } from '../../api/client'
import { describeDraftSaveError } from './draftError'

const instruments: Array<IOPPhasingDemoEye['instrumentCode']> = ['demo_goldmann', 'demo_tono_pen', 'demo_i_care', 'demo_perkins', 'demo_other']
const instrumentLabels: Record<string, string> = { demo_goldmann: 'Demo Goldmann', demo_tono_pen: 'Demo Tono-pen', demo_i_care: 'Demo I-care', demo_perkins: 'Demo Perkins', demo_other: 'Demo other' }
const blankEye = (): IOPPhasingDemoEye => ({ instrumentCode: 'demo_goldmann', dilated: false, comment: '', readings: [{ value: 18, measurementTime: '09:00' }] })

export function IOPPhasingDraftDemo({ csrfToken, episodeId }: { csrfToken: string; episodeId: string }) {
  const [eyeMode, setEyeMode] = useState<IOPPhasingDemoDraftPayload['eyeMode']>('both')
  const [rightEye, setRightEye] = useState<IOPPhasingDemoEye | null>(blankEye())
  const [leftEye, setLeftEye] = useState<IOPPhasingDemoEye | null>(blankEye())
  const save = useMutation({ mutationFn: (payload: IOPPhasingDemoDraftPayload) => episodesAPI.createIOPPhasingDemoDraft(episodeId, csrfToken, payload) })
  function updateMode(mode: IOPPhasingDemoDraftPayload['eyeMode']) { setEyeMode(mode); setRightEye(mode === 'left' ? null : rightEye ?? blankEye()); setLeftEye(mode === 'right' ? null : leftEye ?? blankEye()) }
  function updateEye(side: 'right' | 'left', update: (eye: IOPPhasingDemoEye) => IOPPhasingDemoEye) { const setter = side === 'right' ? setRightEye : setLeftEye; setter(current => current ? update(current) : current) }
  function submit() { save.reset(); save.mutate({ recordMode: 'demo_iop_phasing', profileCode: 'demo_iop_phasing_v1', eyeMode, rightEye, leftEye }) }
  const failure = save.isError ? describeDraftSaveError(save.error, 'demo IOP phasing draft') : ''
  const renderEye = (side: 'right' | 'left', eye: IOPPhasingDemoEye | null) => eye && <fieldset><legend>{side === 'right' ? 'Right eye' : 'Left eye'}</legend><label><span>Demo instrument</span><select value={eye.instrumentCode} onChange={e => updateEye(side, current => ({ ...current, instrumentCode: e.target.value as IOPPhasingDemoEye['instrumentCode'] }))}>{instruments.map(item => <option key={item} value={item}>{instrumentLabels[item]}</option>)}</select></label><label><input type="checkbox" checked={eye.dilated} onChange={e => updateEye(side, current => ({ ...current, dilated: e.target.checked }))} /> Demo dilated</label><div className="phasing-reading-list"><span>Timed readings (mmHg)</span>{eye.readings.map((reading, index) => <div className="phasing-reading" key={`${side}-${index}`}><input aria-label={`${side} eye reading value ${index + 1}`} type="number" min={0} max={100} value={reading.value} onChange={e => updateEye(side, current => ({ ...current, readings: current.readings.map((item, i) => i === index ? { ...item, value: Number(e.target.value) } : item) }))} /><input aria-label={`${side} eye reading time ${index + 1}`} type="time" value={reading.measurementTime} onChange={e => updateEye(side, current => ({ ...current, readings: current.readings.map((item, i) => i === index ? { ...item, measurementTime: e.target.value } : item) }))} /><button type="button" title="Remove reading" aria-label={`Remove ${side} eye reading ${index + 1}`} onClick={() => updateEye(side, current => ({ ...current, readings: current.readings.filter((_, i) => i !== index) }))} disabled={eye.readings.length === 1}><Trash2 size={15} aria-hidden="true" /></button></div>)}<button type="button" onClick={() => updateEye(side, current => ({ ...current, readings: [...current.readings, { value: 18, measurementTime: '12:00' }] }))} disabled={eye.readings.length >= 12}><Plus size={15} aria-hidden="true" /> Add timed reading</button></div><label><span>Demo eye comment</span><textarea maxLength={500} rows={2} value={eye.comment} onChange={e => updateEye(side, current => ({ ...current, comment: e.target.value }))} /></label></fieldset>
  return <section className="examination-draft-demo" aria-labelledby={`phasing-demo-${episodeId}`}><div className="examination-draft-demo-heading"><div><p>Demo</p><h3 id={`phasing-demo-${episodeId}`}>IOP phasing draft</h3></div><Gauge size={18} aria-hidden="true" /></div><p className="examination-draft-demo-note">Timed synthetic readings only. No averages, trends, alerts, device import, clinical observation, or treatment action is created.</p><form className="examination-draft-demo-form" onSubmit={e => { e.preventDefault(); submit() }}><label><span>Eye coverage</span><select value={eyeMode} onChange={e => updateMode(e.target.value as IOPPhasingDemoDraftPayload['eyeMode'])}><option value="right">Right eye</option><option value="left">Left eye</option><option value="both">Both eyes</option></select></label><div className="phasing-eyes">{renderEye('right', rightEye)}{renderEye('left', leftEye)}</div>{failure && <p className="inline-error" role="alert">{failure}</p>}{save.isSuccess && <p className="inline-success" role="status">Demo IOP phasing draft saved. It remains uncommitted.</p>}<button className="primary-button" type="submit" disabled={save.isPending}><Save size={16} aria-hidden="true" />{save.isPending ? 'Saving draft…' : 'Save demo IOP phasing draft'}</button></form></section>
}
