import { Save, Zap } from 'lucide-react'
import { useMutation } from '@tanstack/react-query'
import { useState, type FormEvent } from 'react'
import { episodesAPI, type LaserDemoDraftPayload } from '../../api/client'
import { describeDraftSaveError } from './draftError'

export function LaserDraftDemo({ csrfToken, episodeId }: { csrfToken: string; episodeId: string }) {
  const [eyeMode, setEyeMode] = useState<'both' | 'right' | 'left'>('both'); const [procedure, setProcedure] = useState('demo_procedure_panretinal'); const [site, setSite] = useState('demo_site_main'); const [laser, setLaser] = useState('demo_laser_green'); const [operator, setOperator] = useState('demo_operator_a'); const [date, setDate] = useState(new Date().toISOString().slice(0, 10)); const [comment, setComment] = useState('')
  const save = useMutation({ mutationFn: (payload: LaserDemoDraftPayload) => episodesAPI.createLaserDemoDraft(episodeId, csrfToken, payload) })
  function submit(event: FormEvent) { event.preventDefault(); save.reset(); save.mutate({ recordMode: 'demo_laser', profileCode: 'demo_laser_v1', eyeMode, rightEye: eyeMode === 'left' ? null : { procedureCode: procedure }, leftEye: eyeMode === 'right' ? null : { procedureCode: procedure }, siteCode: site, laserCode: laser, operatorCode: operator, treatmentDate: date, comment }) }
  const failure = save.isError ? describeDraftSaveError(save.error, 'demo laser draft') : ''
  return <section className="examination-draft-demo" aria-labelledby={`laser-demo-${episodeId}`}><div className="examination-draft-demo-heading"><div><p>Demo</p><h3 id={`laser-demo-${episodeId}`}>Laser treatment draft</h3></div><Zap size={18} aria-hidden="true" /></div><p className="examination-draft-demo-note">Synthetic labels only. No laser hardware, energy settings, burns, images, treatment result, or clinical record is created.</p><form className="examination-draft-demo-form" onSubmit={submit}><label><span>Eyes recorded</span><select value={eyeMode} onChange={e => setEyeMode(e.target.value as typeof eyeMode)}><option value="both">Both eyes</option><option value="right">Right eye</option><option value="left">Left eye</option></select></label><label><span>Demo procedure</span><select value={procedure} onChange={e => setProcedure(e.target.value)}><option value="demo_procedure_panretinal">Demo panretinal</option><option value="demo_procedure_grid">Demo grid</option><option value="demo_procedure_focal">Demo focal</option></select></label><label><span>Demo site</span><select value={site} onChange={e => setSite(e.target.value)}><option value="demo_site_main">Demo main site</option><option value="demo_site_outreach">Demo outreach site</option></select></label><label><span>Demo laser</span><select value={laser} onChange={e => setLaser(e.target.value)}><option value="demo_laser_green">Demo green laser</option><option value="demo_laser_yag">Demo YAG laser</option></select></label><label><span>Demo operator</span><select value={operator} onChange={e => setOperator(e.target.value)}><option value="demo_operator_a">Demo operator A</option><option value="demo_operator_b">Demo operator B</option></select></label><label><span>Demo treatment date</span><input type="date" value={date} onChange={e => setDate(e.target.value)} /></label><label><span>Demo comment</span><textarea maxLength={1000} rows={2} value={comment} onChange={e => setComment(e.target.value)} /></label>{failure && <p className="inline-error" role="alert">{failure}</p>}{save.isSuccess && <p className="inline-success" role="status">Demo laser draft saved. It remains uncommitted.</p>}<button className="primary-button" type="submit" disabled={save.isPending}><Save size={16} aria-hidden="true" />{save.isPending ? 'Saving draft…' : 'Save demo draft'}</button></form></section>
}
