import { ClipboardList, Save } from 'lucide-react'
import { useMutation } from '@tanstack/react-query'
import { useState, type FormEvent } from 'react'
import { episodesAPI, type OperationChecklistDemoDraftPayload } from '../../api/client'
import { describeDraftSaveError } from './draftError'

const questionList: Array<{ code: OperationChecklistDemoDraftPayload['questions'][number]['code']; label: string }> = [{ code: 'identity_check', label: 'Identity check discussed' }, { code: 'procedure_confirmed', label: 'Procedure confirmed' }, { code: 'escort_discussed', label: 'Escort discussed' }]
export function OperationChecklistDraftDemo({ csrfToken, episodeId }: { csrfToken: string; episodeId: string }) {
  const [eyeMode, setEyeMode] = useState<'both' | 'right' | 'left'>('both'); const [answers, setAnswers] = useState<Record<string, OperationChecklistDemoDraftPayload['questions'][number]['answer']>>({ identity_check: 'demo_not_recorded', procedure_confirmed: 'demo_not_recorded', escort_discussed: 'demo_not_recorded' }); const [note, setNote] = useState('')
  const save = useMutation({ mutationFn: (payload: OperationChecklistDemoDraftPayload) => episodesAPI.createOperationChecklistDemoDraft(episodeId, csrfToken, payload) })
  function submit(event: FormEvent) { event.preventDefault(); save.reset(); save.mutate({ recordMode: 'demo_operation_checklist', profileCode: 'demo_operation_checklist_v1', eyeMode, questions: questionList.map(q => ({ code: q.code, answer: answers[q.code] ?? 'demo_not_recorded' })), note }) }
  const failure = save.isError ? describeDraftSaveError(save.error, 'demo operation checklist draft') : ''
  return <section className="examination-draft-demo" aria-labelledby={`checklist-demo-${episodeId}`}><div className="examination-draft-demo-heading"><div><p>Demo</p><h3 id={`checklist-demo-${episodeId}`}>Operation checklist draft</h3></div><ClipboardList size={18} aria-hidden="true" /></div><p className="examination-draft-demo-note">Synthetic questionnaire only. It does not admit, discharge, advance theatre workflow, sign, or create a clinical record.</p><form className="examination-draft-demo-form" onSubmit={submit}><label><span>Eye context</span><select value={eyeMode} onChange={e => setEyeMode(e.target.value as typeof eyeMode)}><option value="both">Both eyes</option><option value="right">Right eye</option><option value="left">Left eye</option></select></label>{questionList.map(q => <label key={q.code}><span>{q.label}</span><select value={answers[q.code]} onChange={e => setAnswers({ ...answers, [q.code]: e.target.value as OperationChecklistDemoDraftPayload['questions'][number]['answer'] })}><option value="demo_not_recorded">Not recorded</option><option value="demo_yes">Demo yes</option><option value="demo_no">Demo no</option></select></label>)}<label><span>Demo note</span><textarea maxLength={1000} rows={2} value={note} onChange={e => setNote(e.target.value)} /></label>{failure && <p className="inline-error" role="alert">{failure}</p>}{save.isSuccess && <p className="inline-success" role="status">Demo operation checklist draft saved. It remains uncommitted.</p>}<button className="primary-button" type="submit" disabled={save.isPending}><Save size={16} aria-hidden="true" />{save.isPending ? 'Saving draft…' : 'Save demo draft'}</button></form></section>
}
