/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedClinicFlowRouteImport } from './routes/_authenticated/clinic-flow'
import { Route as AuthenticatedTheatreBookingRouteImport } from './routes/_authenticated/theatre-booking'
import { Route as AuthenticatedPatientsPatientIdRouteImport } from './routes/_authenticated/patients/$patientId'
import { Route as AuthenticatedPatientsSearchRouteImport } from './routes/_authenticated/patients/search'
import { Route as AuthenticatedPatientsPatientIdIndexRouteImport } from './routes/_authenticated/patients/$patientId/index'
import { Route as AuthenticatedPatientsPatientIdExaminationRouteImport } from './routes/_authenticated/patients/$patientId/examination'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedClinicFlowRoute = AuthenticatedClinicFlowRouteImport.update({
  id: '/clinic-flow',
  path: '/clinic-flow',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTheatreBookingRoute =
  AuthenticatedTheatreBookingRouteImport.update({
    id: '/theatre-booking',
    path: '/theatre-booking',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPatientsPatientIdRoute =
  AuthenticatedPatientsPatientIdRouteImport.update({
    id: '/patients/$patientId',
    path: '/patients/$patientId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPatientsSearchRoute =
  AuthenticatedPatientsSearchRouteImport.update({
    id: '/patients/search',
    path: '/patients/search',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPatientsPatientIdIndexRoute =
  AuthenticatedPatientsPatientIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPatientsPatientIdRoute,
  } as any)
const AuthenticatedPatientsPatientIdExaminationRoute =
  AuthenticatedPatientsPatientIdExaminationRouteImport.update({
    id: '/examination',
    path: '/examination',
    getParentRoute: () => AuthenticatedPatientsPatientIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/clinic-flow': typeof AuthenticatedClinicFlowRoute
  '/theatre-booking': typeof AuthenticatedTheatreBookingRoute
  '/patients/$patientId': typeof AuthenticatedPatientsPatientIdRouteWithChildren
  '/patients/search': typeof AuthenticatedPatientsSearchRoute
  '/patients/$patientId/examination': typeof AuthenticatedPatientsPatientIdExaminationRoute
  '/patients/$patientId/': typeof AuthenticatedPatientsPatientIdIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/clinic-flow': typeof AuthenticatedClinicFlowRoute
  '/theatre-booking': typeof AuthenticatedTheatreBookingRoute
  '/': typeof AuthenticatedIndexRoute
  '/patients/search': typeof AuthenticatedPatientsSearchRoute
  '/patients/$patientId/examination': typeof AuthenticatedPatientsPatientIdExaminationRoute
  '/patients/$patientId': typeof AuthenticatedPatientsPatientIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/clinic-flow': typeof AuthenticatedClinicFlowRoute
  '/_authenticated/theatre-booking': typeof AuthenticatedTheatreBookingRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/patients/$patientId': typeof AuthenticatedPatientsPatientIdRouteWithChildren
  '/_authenticated/patients/search': typeof AuthenticatedPatientsSearchRoute
  '/_authenticated/patients/$patientId/examination': typeof AuthenticatedPatientsPatientIdExaminationRoute
  '/_authenticated/patients/$patientId/': typeof AuthenticatedPatientsPatientIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/clinic-flow'
    | '/theatre-booking'
    | '/patients/$patientId'
    | '/patients/search'
    | '/patients/$patientId/examination'
    | '/patients/$patientId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/clinic-flow'
    | '/theatre-booking'
    | '/'
    | '/patients/search'
    | '/patients/$patientId/examination'
    | '/patients/$patientId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/clinic-flow'
    | '/_authenticated/theatre-booking'
    | '/_authenticated/'
    | '/_authenticated/patients/$patientId'
    | '/_authenticated/patients/search'
    | '/_authenticated/patients/$patientId/examination'
    | '/_authenticated/patients/$patientId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clinic-flow': {
      id: '/_authenticated/clinic-flow'
      path: '/clinic-flow'
      fullPath: '/clinic-flow'
      preLoaderRoute: typeof AuthenticatedClinicFlowRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/theatre-booking': {
      id: '/_authenticated/theatre-booking'
      path: '/theatre-booking'
      fullPath: '/theatre-booking'
      preLoaderRoute: typeof AuthenticatedTheatreBookingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/patients/$patientId': {
      id: '/_authenticated/patients/$patientId'
      path: '/patients/$patientId'
      fullPath: '/patients/$patientId'
      preLoaderRoute: typeof AuthenticatedPatientsPatientIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/patients/search': {
      id: '/_authenticated/patients/search'
      path: '/patients/search'
      fullPath: '/patients/search'
      preLoaderRoute: typeof AuthenticatedPatientsSearchRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/patients/$patientId/': {
      id: '/_authenticated/patients/$patientId/'
      path: '/'
      fullPath: '/patients/$patientId/'
      preLoaderRoute: typeof AuthenticatedPatientsPatientIdIndexRouteImport
      parentRoute: typeof AuthenticatedPatientsPatientIdRoute
    }
    '/_authenticated/patients/$patientId/examination': {
      id: '/_authenticated/patients/$patientId/examination'
      path: '/examination'
      fullPath: '/patients/$patientId/examination'
      preLoaderRoute: typeof AuthenticatedPatientsPatientIdExaminationRouteImport
      parentRoute: typeof AuthenticatedPatientsPatientIdRoute
    }
  }
}

interface AuthenticatedPatientsPatientIdRouteChildren {
  AuthenticatedPatientsPatientIdExaminationRoute: typeof AuthenticatedPatientsPatientIdExaminationRoute
  AuthenticatedPatientsPatientIdIndexRoute: typeof AuthenticatedPatientsPatientIdIndexRoute
}

const AuthenticatedPatientsPatientIdRouteChildren: AuthenticatedPatientsPatientIdRouteChildren =
  {
    AuthenticatedPatientsPatientIdExaminationRoute:
      AuthenticatedPatientsPatientIdExaminationRoute,
    AuthenticatedPatientsPatientIdIndexRoute:
      AuthenticatedPatientsPatientIdIndexRoute,
  }

const AuthenticatedPatientsPatientIdRouteWithChildren =
  AuthenticatedPatientsPatientIdRoute._addFileChildren(
    AuthenticatedPatientsPatientIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedClinicFlowRoute: typeof AuthenticatedClinicFlowRoute
  AuthenticatedTheatreBookingRoute: typeof AuthenticatedTheatreBookingRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedPatientsPatientIdRoute: typeof AuthenticatedPatientsPatientIdRouteWithChildren
  AuthenticatedPatientsSearchRoute: typeof AuthenticatedPatientsSearchRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedClinicFlowRoute: AuthenticatedClinicFlowRoute,
  AuthenticatedTheatreBookingRoute: AuthenticatedTheatreBookingRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedPatientsPatientIdRoute:
    AuthenticatedPatientsPatientIdRouteWithChildren,
  AuthenticatedPatientsSearchRoute: AuthenticatedPatientsSearchRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
