import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { useState } from 'react'
import { createFileRoute } from '@tanstack/react-router'
import { Building2, History, Settings, Users, Plug } from 'lucide-react'

import { adminAPI } from '../../api/client'
import { sessionQuery } from '../../features/auth/queries'
import { presentationTerminology } from '../../config/terminology'

export const Route = createFileRoute('/_authenticated/admin')({ component: AdminPage })

function settingGroup(key: string) {
  if (key.startsWith('clinic_flow')) return 'Clinic flow'
  if (key.startsWith('theatre_')) return 'Theatre'
  if (key.startsWith('referral_')) return 'Referrals'
  if (key.startsWith('correspondence_')) return 'Correspondence'
  if (key.startsWith('messaging_')) return 'Messaging'
  return 'General'
}

function settingLabel(key: string) {
  return key.replaceAll('_', ' ')
}

function AdminPage() {
  const [activeSection, setActiveSection] = useState<'users' | 'organization' | 'settings' | 'catalogues' | 'audit' | 'capabilities' | 'integrations'>('users')
  const { data: users = [], isError: usersError } = useQuery({ queryKey: ['admin', 'users'], queryFn: adminAPI.users })
  const { data: roles = [], isError: rolesError } = useQuery({ queryKey: ['admin', 'roles'], queryFn: adminAPI.roles })
  const { data: contexts, isError: contextsError } = useQuery({ queryKey: ['admin', 'contexts'], queryFn: adminAPI.contexts })
  const { data: settings = [], isError: settingsError } = useQuery({ queryKey: ['admin', 'settings'], queryFn: adminAPI.settings })
  const [auditFilter, setAuditFilter] = useState({ command: '', outcome: '', targetType: '', actor: '' })
  const { data: audit = [], isError: auditError } = useQuery({ queryKey: ['admin', 'audit', auditFilter], queryFn: () => adminAPI.audit(auditFilter) })
  const { data: integrations = [], isError: integrationsError } = useQuery({ queryKey: ['admin', 'integrations'], queryFn: adminAPI.integrations })
  const { data: capabilities = [], isError: capabilitiesError } = useQuery({ queryKey: ['admin', 'capabilities'], queryFn: adminAPI.capabilities })
  const { data: catalogue = [], isError: catalogueError } = useQuery({ queryKey: ['admin', 'prescription-catalogue'], queryFn: adminAPI.prescriptionCatalogue })
  const { data: theatreCatalogue = [], isError: theatreCatalogueError } = useQuery({ queryKey: ['admin', 'theatre-procedure-catalogue'], queryFn: adminAPI.theatreProcedureCatalogue })
  const { data: clinicalCatalogue = [], isError: clinicalCatalogueError } = useQuery({ queryKey: ['admin', 'clinical-reference-catalogue'], queryFn: adminAPI.clinicalReferenceCatalogue })
  const { data: session } = useQuery(sessionQuery)
  const queryClient = useQueryClient()
  const [editing, setEditing] = useState<string | null>(null)
  const [username, setUsername] = useState('')
  const [displayName, setDisplayName] = useState('')
  const [password, setPassword] = useState('')
  const [role, setRole] = useState('clinical_user')
  const [siteId, setSiteId] = useState('')
  const [firmId, setFirmId] = useState('')
  const [userMessage, setUserMessage] = useState<string | null>(null)
  const [userError, setUserError] = useState<string | null>(null)
  const [contextKind, setContextKind] = useState<'site' | 'firm'>('site')
  const [contextID, setContextID] = useState<number | null>(null)
  const [contextName, setContextName] = useState('')
  const [contextMessage, setContextMessage] = useState<string | null>(null)
  const [contextError, setContextError] = useState<string | null>(null)
  const [catalogueEditing, setCatalogueEditing] = useState<number | null>(null)
  const [catalogueCategory, setCatalogueCategory] = useState<'medication' | 'route' | 'frequency' | 'duration' | 'laterality' | 'procedure' | 'biometry' | 'laser' | 'intravitreal' | 'lab' | 'genetics' | 'dna' | 'consent' | 'examination'>('medication')
  const [catalogueCode, setCatalogueCode] = useState('development_')
  const [catalogueName, setCatalogueName] = useState('')
  const [catalogueOrder, setCatalogueOrder] = useState('0')
  const [catalogueMessage, setCatalogueMessage] = useState<string | null>(null)
  const [catalogueErrorMessage, setCatalogueErrorMessage] = useState<string | null>(null)
  const [theatreEditing, setTheatreEditing] = useState<number | null>(null)
  const [theatreCode, setTheatreCode] = useState('development_')
  const [theatreName, setTheatreName] = useState('')
  const [theatreOrder, setTheatreOrder] = useState('0')
  const [theatreMessage, setTheatreMessage] = useState<string | null>(null)
  const [theatreErrorMessage, setTheatreErrorMessage] = useState<string | null>(null)
  const [clinicalEditing, setClinicalEditing] = useState<number | null>(null)
  const [clinicalDomain, setClinicalDomain] = useState<'biometry' | 'laser' | 'intravitreal' | 'lab' | 'genetics' | 'dna' | 'consent' | 'examination'>('biometry')
  const [clinicalCode, setClinicalCode] = useState('development_')
  const [clinicalName, setClinicalName] = useState('')
  const [clinicalOrder, setClinicalOrder] = useState('0')
  const [clinicalMessage, setClinicalMessage] = useState<string | null>(null)
  const [clinicalErrorMessage, setClinicalErrorMessage] = useState<string | null>(null)
  const userMutation = useMutation({ mutationFn: ({ id, version, active }: { id: string; version: number; active: boolean }) => adminAPI.setUserActive(id, version, active, session?.csrfToken ?? ''), onSuccess: () => { void queryClient.invalidateQueries({ queryKey: ['admin'] }) } })
  const roleMutation = useMutation({ mutationFn: ({ userId, roleId, revoke }: { userId: string; roleId: number; revoke: boolean }) => revoke ? adminAPI.revokeRole(userId, roleId, session?.csrfToken ?? '') : adminAPI.assignRole(userId, roleId, session?.csrfToken ?? ''), onSuccess: () => { setUserMessage('Role assignment updated successfully.'); void queryClient.invalidateQueries({ queryKey: ['admin', 'users'] }); void queryClient.invalidateQueries({ queryKey: ['admin', 'audit'] }) }, onError: error => setUserError(error instanceof Error ? error.message : 'The role assignment could not be updated.') })
  const settingMutation = useMutation({ mutationFn: ({ key, value, version }: { key: string; value: string; version: number }) => adminAPI.updateSetting(key, value, version, session?.csrfToken ?? ''), onSuccess: () => { void queryClient.invalidateQueries({ queryKey: ['admin'] }) } })
  const capabilityMutation = useMutation({ mutationFn: ({ key, enabled, version }: { key: string; enabled: boolean; version: number }) => adminAPI.setCapability(key, enabled, version, session?.csrfToken ?? ''), onSuccess: () => { void queryClient.invalidateQueries({ queryKey: ['admin', 'capabilities'] }) } })
  const contextSave = useMutation({ mutationFn: () => { const csrf = session?.csrfToken ?? ''; const version = (contextKind === 'site' ? contexts?.sites : contexts?.firms)?.find(item => item.id === contextID)?.version ?? 0; if (contextKind === 'site') return contextID ? adminAPI.updateSite(contextID, contextName, true, version, csrf) : adminAPI.createSite(contextName, csrf); return contextID ? adminAPI.updateFirm(contextID, contextName, true, version, csrf) : adminAPI.createFirm(contextName, csrf) }, onMutate: () => { setContextMessage(null); setContextError(null) }, onSuccess: () => { setContextID(null); setContextName(''); setContextMessage(`${contextKind === 'site' ? 'Site' : 'Firm'} saved successfully.`); void queryClient.invalidateQueries({ queryKey: ['admin'] }) }, onError: error => setContextError(error instanceof Error ? error.message : 'The organization change could not be saved.') })
  const contextActive = useMutation({ mutationFn: ({ kind, id, name, version, active }: { kind: 'site' | 'firm'; id: number; name: string; version: number; active: boolean }) => kind === 'site' ? adminAPI.setSiteActive(id, name, version, active, session?.csrfToken ?? '') : adminAPI.setFirmActive(id, name, version, active, session?.csrfToken ?? ''), onSuccess: () => { void queryClient.invalidateQueries({ queryKey: ['admin'] }) }, onError: error => setContextError(error instanceof Error ? error.message : 'The organization status could not be changed.') })
  const catalogueSave = useMutation({ mutationFn: () => { const body = { category: catalogueCategory, code: catalogueCode.trim(), displayName: catalogueName.trim(), active: true, displayOrder: Number(catalogueOrder) }; const csrf = session?.csrfToken ?? ''; if (catalogueEditing) return adminAPI.updatePrescriptionCatalogue(catalogueEditing, { ...body, active: catalogue.find(item => item.id === catalogueEditing)?.active ?? true, expectedVersion: catalogue.find(item => item.id === catalogueEditing)?.version ?? 0 }, csrf); return adminAPI.createPrescriptionCatalogue(body, csrf) }, onMutate: () => { setCatalogueMessage(null); setCatalogueErrorMessage(null) }, onSuccess: () => { setCatalogueEditing(null); setCatalogueCode('development_'); setCatalogueName(''); setCatalogueOrder('0'); setCatalogueMessage('Synthetic catalogue item saved successfully.'); void queryClient.invalidateQueries({ queryKey: ['admin', 'prescription-catalogue'] }) }, onError: error => setCatalogueErrorMessage(error instanceof Error ? error.message : 'The synthetic catalogue item could not be saved.') })
  const catalogueActive = useMutation({ mutationFn: (item: typeof catalogue[number]) => adminAPI.updatePrescriptionCatalogue(item.id, { category: item.category, code: item.code, displayName: item.displayName, active: !item.active, displayOrder: item.displayOrder, expectedVersion: item.version }, session?.csrfToken ?? ''), onMutate: () => { setCatalogueMessage(null); setCatalogueErrorMessage(null) }, onSuccess: (_item, item) => { setCatalogueMessage(`Synthetic catalogue item ${item.active ? 'deactivated' : 'reactivated'} successfully.`); void queryClient.invalidateQueries({ queryKey: ['admin', 'prescription-catalogue'] }) }, onError: error => setCatalogueErrorMessage(error instanceof Error ? error.message : 'The synthetic catalogue status could not be changed.') })
  const theatreSave = useMutation({ mutationFn: () => { const body = { category: 'procedure' as const, code: theatreCode.trim(), displayName: theatreName.trim(), active: true, displayOrder: Number(theatreOrder) }; const csrf = session?.csrfToken ?? ''; if (theatreEditing) { const current = theatreCatalogue.find(item => item.id === theatreEditing); return adminAPI.updateTheatreProcedureCatalogue(theatreEditing, { ...body, active: current?.active ?? true, expectedVersion: current?.version ?? 0 }, csrf) }; return adminAPI.createTheatreProcedureCatalogue(body, csrf) }, onMutate: () => { setTheatreMessage(null); setTheatreErrorMessage(null) }, onSuccess: () => { setTheatreEditing(null); setTheatreCode('development_'); setTheatreName(''); setTheatreOrder('0'); setTheatreMessage('Synthetic theatre procedure saved successfully.'); void queryClient.invalidateQueries({ queryKey: ['admin', 'theatre-procedure-catalogue'] }) }, onError: error => setTheatreErrorMessage(error instanceof Error ? error.message : 'The synthetic theatre procedure could not be saved.') })
  const theatreActive = useMutation({ mutationFn: (item: typeof theatreCatalogue[number]) => adminAPI.updateTheatreProcedureCatalogue(item.id, { category: 'procedure', code: item.code, displayName: item.displayName, active: !item.active, displayOrder: item.displayOrder, expectedVersion: item.version }, session?.csrfToken ?? ''), onMutate: () => { setTheatreMessage(null); setTheatreErrorMessage(null) }, onSuccess: (_item, item) => { setTheatreMessage(`Synthetic theatre procedure ${item.active ? 'deactivated' : 'reactivated'} successfully.`); void queryClient.invalidateQueries({ queryKey: ['admin', 'theatre-procedure-catalogue'] }) }, onError: error => setTheatreErrorMessage(error instanceof Error ? error.message : 'The synthetic theatre procedure status could not be changed.') })
  const clinicalSave = useMutation({ mutationFn: () => { const body = { category: clinicalDomain, code: clinicalCode.trim(), displayName: clinicalName.trim(), active: true, displayOrder: Number(clinicalOrder) }; const csrf = session?.csrfToken ?? ''; if (clinicalEditing) { const current = clinicalCatalogue.find(item => item.id === clinicalEditing); return adminAPI.updateClinicalReferenceCatalogue(clinicalEditing, { ...body, active: current?.active ?? true, expectedVersion: current?.version ?? 0 }, csrf) }; return adminAPI.createClinicalReferenceCatalogue(body, csrf) }, onMutate: () => { setClinicalMessage(null); setClinicalErrorMessage(null) }, onSuccess: () => { setClinicalEditing(null); setClinicalCode('development_'); setClinicalName(''); setClinicalOrder('0'); setClinicalMessage('Synthetic clinical catalogue item saved successfully.'); void queryClient.invalidateQueries({ queryKey: ['admin', 'clinical-reference-catalogue'] }) }, onError: error => setClinicalErrorMessage(error instanceof Error ? error.message : 'The synthetic clinical catalogue item could not be saved.') })
  const clinicalActive = useMutation({ mutationFn: (item: typeof clinicalCatalogue[number]) => adminAPI.updateClinicalReferenceCatalogue(item.id, { category: item.category, code: item.code, displayName: item.displayName, active: !item.active, displayOrder: item.displayOrder, expectedVersion: item.version }, session?.csrfToken ?? ''), onMutate: () => { setClinicalMessage(null); setClinicalErrorMessage(null) }, onSuccess: (_item, item) => { setClinicalMessage(`Synthetic clinical catalogue item ${item.active ? 'deactivated' : 'reactivated'} successfully.`); void queryClient.invalidateQueries({ queryKey: ['admin', 'clinical-reference-catalogue'] }) }, onError: error => setClinicalErrorMessage(error instanceof Error ? error.message : 'The synthetic clinical catalogue status could not be changed.') })
  const userSave = useMutation({ mutationFn: () => editing ? adminAPI.updateUser(editing, { username, displayName, password: password || undefined, role, siteIds: siteId ? [Number(siteId)] : [], firmIds: firmId ? [Number(firmId)] : [], expectedVersion: users.find(user => user.id === editing)?.version ?? 0 }, session?.csrfToken ?? '') : adminAPI.createUser({ username, displayName, password, role, siteIds: siteId ? [Number(siteId)] : [], firmIds: firmId ? [Number(firmId)] : [] }, session?.csrfToken ?? ''), onMutate: () => { setUserMessage(null); setUserError(null) }, onSuccess: () => { setEditing(null); setUsername(''); setDisplayName(''); setPassword(''); setRole('clinical_user'); setSiteId(''); setFirmId(''); setUserMessage(editing ? 'Synthetic user updated successfully.' : 'Synthetic user created successfully.'); void queryClient.invalidateQueries({ queryKey: ['admin'] }) }, onError: (error) => { setUserError(error instanceof Error ? error.message : 'The user could not be saved.') } })
  if (!session?.permissions.includes('admin.development.read') || usersError || rolesError || contextsError || settingsError || auditError || integrationsError || capabilitiesError || catalogueError || theatreCatalogueError || clinicalCatalogueError) {
    return <div className="admin-workspace"><div className="workspace-title"><p>{presentationTerminology.environmentHeading}</p><h1>Access restricted</h1><span>Your current role cannot view administration settings.</span></div></div>
  }

  return <div className={`admin-workspace admin-view-${activeSection}`}>
    <div className="workspace-title"><p>{presentationTerminology.environmentHeading}</p><h1>Admin &amp; configuration</h1><span>Seeded synthetic settings and users only. No production records are changed.</span></div>
    <nav className="admin-section-nav" aria-label="Administration sections">
      <button type="button" className={activeSection === 'users' ? 'active' : ''} aria-current={activeSection === 'users' ? 'page' : undefined} onClick={() => setActiveSection('users')}>Users &amp; access</button>
      <button type="button" className={activeSection === 'organization' ? 'active' : ''} aria-current={activeSection === 'organization' ? 'page' : undefined} onClick={() => setActiveSection('organization')}>Organization</button>
      <button type="button" className={activeSection === 'settings' ? 'active' : ''} aria-current={activeSection === 'settings' ? 'page' : undefined} onClick={() => setActiveSection('settings')}>Operational settings</button>
      <button type="button" className={activeSection === 'catalogues' ? 'active' : ''} aria-current={activeSection === 'catalogues' ? 'page' : undefined} onClick={() => setActiveSection('catalogues')}>Clinical catalogues</button>
      <button type="button" className={activeSection === 'audit' ? 'active' : ''} aria-current={activeSection === 'audit' ? 'page' : undefined} onClick={() => setActiveSection('audit')}>Audit history</button>
      <button type="button" className={activeSection === 'capabilities' ? 'active' : ''} aria-current={activeSection === 'capabilities' ? 'page' : undefined} onClick={() => setActiveSection('capabilities')}>Capabilities</button>
      <button type="button" className={activeSection === 'integrations' ? 'active' : ''} aria-current={activeSection === 'integrations' ? 'page' : undefined} onClick={() => setActiveSection('integrations')}>Integrations</button>
    </nav>
    <div className="admin-grid">
      <section className="admin-panel"><h2><Users size={18} /> Users</h2>
        <details className="admin-role-catalogue"><summary>Available roles and permissions</summary>{roles.map(item => <div className="admin-role" key={item.id}><strong>{item.name}</strong><small>{item.scope} scope · {item.description}</small><small>{item.permissions.join(', ') || 'No permissions'}</small></div>)}</details>
        <form className="admin-user-form" onSubmit={event => { event.preventDefault(); userSave.mutate() }}>
          <strong>{editing ? 'Edit synthetic user' : 'Create synthetic user'}</strong>
          <label>Username<input required pattern="[a-z0-9._-]+" value={username} onChange={event => setUsername(event.target.value)} /></label>
          <label>Display name<input required value={displayName} onChange={event => setDisplayName(event.target.value)} /></label>
          <label>Password{editing ? ' (optional)' : ''}<input required={!editing} minLength={6} type="password" value={password} onChange={event => setPassword(event.target.value)} /></label>
          <label>Role<select value={role} onChange={event => setRole(event.target.value)}>{roles.filter(item => item.scope === 'institution').map(item => <option key={item.id} value={item.name === 'Institution Administrator' ? 'institution_administrator' : 'clinical_user'}>{item.name}</option>)}</select></label>
          <label>Site<select value={siteId} onChange={event => setSiteId(event.target.value)}><option value="">No site membership</option>{contexts?.sites.filter(site => site.active !== false).map(site => <option key={site.id} value={site.id}>{site.name}</option>)}</select></label>
          <label>Firm<select value={firmId} onChange={event => setFirmId(event.target.value)}><option value="">No firm membership</option>{contexts?.firms.filter(firm => firm.active !== false).map(firm => <option key={firm.id} value={firm.id}>{firm.name}</option>)}</select></label>
          <span><button className="small-action" type="submit" disabled={userSave.isPending}>{userSave.isPending ? 'Saving…' : editing ? 'Update user' : 'Create user'}</button>{editing && <button className="small-action" type="button" onClick={() => setEditing(null)}>Cancel</button>}</span>
          {userError && <p className="inline-error" role="alert">{userError}</p>}
          {userMessage && <p className="inline-success" role="status">{userMessage}</p>}
        </form>
        {users.map(user => <div className="admin-row" key={user.id}><strong>{user.displayName}<small>{user.username}</small></strong><span>{user.role.replaceAll('_', ' ')}<small>{(user.permissions ?? []).join(', ') || 'No permissions'}</small><small>Roles: {(user.roles ?? []).filter(item => item.active).map(item => item.roleName).join(', ') || 'None'}</small></span><span>{user.active ? 'Active' : 'Inactive'} <button className="small-action" type="button" onClick={() => userMutation.mutate({ id: user.id, version: user.version, active: !user.active })}>{user.active ? 'Deactivate' : 'Reactivate'}</button> <button className="small-action" type="button" onClick={() => { setEditing(user.id); setUsername(user.username); setDisplayName(user.displayName); setRole(user.role); setPassword(''); setSiteId(String(user.sites?.[0]?.id ?? '')); setFirmId(String(user.firms?.[0]?.id ?? '')) }}>Edit</button>{(user.roles ?? []).filter(item => item.active).map(item => <button key={item.id} className="small-action" type="button" onClick={() => roleMutation.mutate({ userId: user.id, roleId: item.roleId, revoke: true })}>Revoke {item.roleName}</button>)}</span></div>)}
      </section>
      <section className="admin-panel"><h2><Building2 size={18} /> Organization</h2><p><strong>{contexts?.institution.name}</strong></p><p className="muted">Current context: {session?.context.site.name} / {session?.context.firm.name}</p><form className="admin-context-form" onSubmit={event => { event.preventDefault(); contextSave.mutate() }}><strong>{contextID ? `Edit ${contextKind}` : 'Add synthetic context'}</strong><select aria-label="Context type" value={contextKind} onChange={event => { setContextKind(event.target.value as 'site' | 'firm'); setContextID(null); setContextName('') }}><option value="site">Site</option><option value="firm">Firm</option></select><input aria-label="Context name" required value={contextName} onChange={event => setContextName(event.target.value)} placeholder="Name" /><button className="small-action" type="submit" disabled={contextSave.isPending}>{contextSave.isPending ? 'Saving…' : contextID ? 'Update' : 'Add'}</button>{contextID && <button className="small-action" type="button" onClick={() => { setContextID(null); setContextName('') }}>Cancel</button>}</form>{contextError && <p className="inline-error" role="alert">{contextError}</p>}{contextMessage && <p className="inline-success" role="status">{contextMessage}</p>}<div className="admin-context-list"><strong>Sites</strong>{contexts?.sites.map(item => <div className="admin-row" key={`site-${item.id}`}><span>{item.name}</span><span>{item.active ? 'Active' : 'Inactive'}</span><span><button className="small-action" type="button" onClick={() => { setContextKind('site'); setContextID(item.id); setContextName(item.name) }}>Edit</button><button className="small-action" type="button" onClick={() => contextActive.mutate({ kind: 'site', id: item.id, name: item.name, version: item.version ?? 1, active: !item.active })}>{item.active ? 'Deactivate' : 'Reactivate'}</button></span></div>)}<strong>Firms</strong>{contexts?.firms.map(item => <div className="admin-row" key={`firm-${item.id}`}><span>{item.name}</span><span>{item.active ? 'Active' : 'Inactive'}</span><span><button className="small-action" type="button" onClick={() => { setContextKind('firm'); setContextID(item.id); setContextName(item.name) }}>Edit</button><button className="small-action" type="button" onClick={() => contextActive.mutate({ kind: 'firm', id: item.id, name: item.name, version: item.version ?? 1, active: !item.active })}>{item.active ? 'Deactivate' : 'Reactivate'}</button></span></div>)}</div></section>
      <section className="admin-panel"><h2><Settings size={18} /> Operational configuration</h2>{settings.map((setting, index) => <div key={setting.key}>{(index === 0 || settingGroup(settings[index - 1]?.key ?? '') !== settingGroup(setting.key)) && <h3 className="admin-setting-group">{settingGroup(setting.key)}</h3>}<div className="admin-row"><span>{settingLabel(setting.key)}<small>Effective scope: {setting.scope} · source: {setting.source}</small></span><span>{setting.key === 'default_site' || setting.key === 'default_firm' ? <select aria-label={setting.key} value={setting.value} onChange={event => settingMutation.mutate({ key: setting.key, value: event.target.value, version: setting.version })}>{(setting.key === 'default_site' ? contexts?.sites : contexts?.firms)?.filter(item => item.active).map(item => <option key={item.id} value={item.name}>{item.name}</option>)}</select> : <input aria-label={setting.key} defaultValue={setting.value} onBlur={event => { const value = event.currentTarget.value; if (value !== setting.value) settingMutation.mutate({ key: setting.key, value, version: setting.version }) }} />}</span></div></div>)}</section>
      <section className="admin-panel"><h2><Settings size={18} /> Medication catalogue</h2><p className="muted">Synthetic demo catalogue only. Changes affect demonstration drafts, not prescriptions or clinical records.</p><form className="admin-catalogue-form" onSubmit={event => { event.preventDefault(); catalogueSave.mutate() }}><select aria-label="Catalogue category" value={catalogueCategory} onChange={event => setCatalogueCategory(event.target.value as typeof catalogueCategory)}><option value="medication">Medication</option><option value="route">Route</option><option value="frequency">Frequency</option><option value="duration">Duration</option><option value="laterality">Laterality</option></select><input aria-label="Catalogue code" required pattern="development_[a-z0-9_]+" value={catalogueCode} onChange={event => setCatalogueCode(event.target.value)} /><input aria-label="Catalogue display name" required value={catalogueName} onChange={event => setCatalogueName(event.target.value)} placeholder="Display name" /><input aria-label="Catalogue display order" required type="number" min="0" value={catalogueOrder} onChange={event => setCatalogueOrder(event.target.value)} /><button className="small-action" type="submit" disabled={catalogueSave.isPending}>{catalogueSave.isPending ? 'Saving…' : catalogueEditing ? 'Update item' : 'Add item'}</button>{catalogueEditing && <button className="small-action" type="button" onClick={() => { setCatalogueEditing(null); setCatalogueCode('development_'); setCatalogueName(''); setCatalogueOrder('0') }}>Cancel</button>}</form>{catalogueErrorMessage && <p className="inline-error" role="alert">{catalogueErrorMessage}</p>}{catalogueMessage && <p className="inline-success" role="status">{catalogueMessage}</p>}<div className="admin-catalogue-list">{catalogue.map(item => <div className="admin-row" key={item.id}><strong>{item.displayName}<small>{item.category} · {item.code}</small></strong><span>{item.active ? 'Active' : 'Inactive'}<small>Order {item.displayOrder}</small></span><span><button className="small-action" type="button" onClick={() => { setCatalogueEditing(item.id); setCatalogueCategory(item.category); setCatalogueCode(item.code); setCatalogueName(item.displayName); setCatalogueOrder(String(item.displayOrder)) }}>Edit</button><button className="small-action" type="button" onClick={() => catalogueActive.mutate(item)} disabled={catalogueActive.isPending}>{item.active ? 'Deactivate' : 'Reactivate'}</button></span></div>)}</div></section>
      <section className="admin-panel admin-audit-panel"><h2><History size={18} /> Audit history</h2><p className="muted">Append-only record of synthetic administration changes in the current institution.</p><div className="admin-audit-filters"><input aria-label="Filter audit actor" placeholder="Actor" value={auditFilter.actor} onChange={e => setAuditFilter({ ...auditFilter, actor: e.target.value })} /><input aria-label="Filter audit command" placeholder="Command" value={auditFilter.command} onChange={e => setAuditFilter({ ...auditFilter, command: e.target.value })} /><select aria-label="Filter audit outcome" value={auditFilter.outcome} onChange={e => setAuditFilter({ ...auditFilter, outcome: e.target.value })}><option value="">All outcomes</option><option value="success">Success</option><option value="failure">Failure</option><option value="denied">Denied</option></select><select aria-label="Filter audit target" value={auditFilter.targetType} onChange={e => setAuditFilter({ ...auditFilter, targetType: e.target.value })}><option value="">All targets</option><option value="user">User</option><option value="setting">Setting</option><option value="capability">Capability</option></select></div>{audit.length === 0 ? <p className="muted">No administration events match these filters.</p> : <div className="admin-audit-list">{audit.map((event, index) => <article className="admin-audit-event" key={`${event.command}-${event.createdAt}-${index}`}><div><strong>{event.command.replaceAll('.', ' ')}</strong><span className={`audit-outcome audit-${event.outcome}`}>{event.outcome}</span></div><p><strong>Actor:</strong> {event.actorDisplayName} · <strong>Target:</strong> {event.targetDisplayName ?? event.targetKey ?? event.targetType}</p><p><strong>Scope:</strong> {event.scope} · <strong>Changed:</strong> {event.changedFields.join(', ') || 'No fields recorded'}</p>{(event.before && Object.keys(event.before).length > 0 || event.after && Object.keys(event.after).length > 0) && <p><strong>Before → after:</strong> {JSON.stringify(event.before)} → {JSON.stringify(event.after)}</p>}<small>{new Date(event.createdAt).toLocaleString()} · Correlation ID: {event.correlationId}</small></article>)}</div>}</section>
      <section className="admin-panel"><h2><Plug size={18} /> Integration settings</h2><p className="muted">Read-only placeholders for future clinic integrations. No external connections or data transfer are enabled.</p>{integrations.map(item => <div className="admin-row" key={item.key}><span><strong>{item.displayName}</strong><small>{item.description}</small></span><span>{item.status}</span></div>)}</section>
      <section className="admin-panel"><h2><Settings size={18} /> Capability profile</h2><p className="muted">Enable only the demonstration modules this clinic needs. Disabled capabilities are a configuration boundary; server enforcement is applied as each module adopts the registry.</p>{capabilities.map(capability => <div className="admin-row" key={capability.key}><span><strong>{capability.displayName}</strong><small>{capability.description}</small></span><span>{capability.enabled ? 'Enabled' : 'Disabled'}</span><button className="small-action" type="button" onClick={() => capabilityMutation.mutate({ key: capability.key, enabled: !capability.enabled, version: capability.version })} disabled={capabilityMutation.isPending}>{capability.enabled ? 'Disable' : 'Enable'}</button></div>)}</section>
      <section className="admin-panel"><h2><Settings size={18} /> Theatre procedure catalogue</h2><p className="muted">Synthetic procedures used by the demonstration theatre workflow only. No clinical procedure or real booking is created.</p><form className="admin-catalogue-form" onSubmit={event => { event.preventDefault(); theatreSave.mutate() }}><input aria-label="Theatre procedure code" required pattern="development_[a-z0-9_]+" value={theatreCode} onChange={event => setTheatreCode(event.target.value)} /><input aria-label="Theatre procedure display name" required value={theatreName} onChange={event => setTheatreName(event.target.value)} placeholder="Display name" /><input aria-label="Theatre procedure display order" required type="number" min="0" value={theatreOrder} onChange={event => setTheatreOrder(event.target.value)} /><button className="small-action" type="submit" disabled={theatreSave.isPending}>{theatreSave.isPending ? 'Saving…' : theatreEditing ? 'Update procedure' : 'Add procedure'}</button>{theatreEditing && <button className="small-action" type="button" onClick={() => { setTheatreEditing(null); setTheatreCode('development_'); setTheatreName(''); setTheatreOrder('0') }}>Cancel</button>}</form>{theatreErrorMessage && <p className="inline-error" role="alert">{theatreErrorMessage}</p>}{theatreMessage && <p className="inline-success" role="status">{theatreMessage}</p>}<div className="admin-catalogue-list">{theatreCatalogue.map(item => <div className="admin-row" key={item.id}><strong>{item.displayName}<small>{item.code}</small></strong><span>{item.active ? 'Active' : 'Inactive'}<small>Order {item.displayOrder}</small></span><span><button className="small-action" type="button" onClick={() => { setTheatreEditing(item.id); setTheatreCode(item.code); setTheatreName(item.displayName); setTheatreOrder(String(item.displayOrder)) }}>Edit</button><button className="small-action" type="button" onClick={() => theatreActive.mutate(item)} disabled={theatreActive.isPending}>{item.active ? 'Deactivate' : 'Reactivate'}</button></span></div>)}</div></section>
      <section className="admin-panel"><h2><Settings size={18} /> Clinical reference catalogues</h2><p className="muted">Synthetic reference values for the demonstration only. These are not production clinical standards or terminology imports.</p><form className="admin-catalogue-form" onSubmit={event => { event.preventDefault(); clinicalSave.mutate() }}><select aria-label="Clinical catalogue domain" value={clinicalDomain} onChange={event => setClinicalDomain(event.target.value as typeof clinicalDomain)}><option value="biometry">Biometry lenses</option><option value="laser">Laser procedures</option><option value="intravitreal">Intravitreal drugs</option><option value="lab">Lab results</option><option value="genetics">Genetic results</option><option value="dna">DNA extraction</option><option value="consent">Consent</option><option value="examination">Examination</option></select><input aria-label="Clinical catalogue code" required pattern="development_[a-z0-9_]+" value={clinicalCode} onChange={event => setClinicalCode(event.target.value)} /><input aria-label="Clinical catalogue display name" required value={clinicalName} onChange={event => setClinicalName(event.target.value)} placeholder="Display name" /><input aria-label="Clinical catalogue display order" required type="number" min="0" value={clinicalOrder} onChange={event => setClinicalOrder(event.target.value)} /><button className="small-action" type="submit" disabled={clinicalSave.isPending}>{clinicalSave.isPending ? 'Saving…' : clinicalEditing ? 'Update item' : 'Add item'}</button>{clinicalEditing && <button className="small-action" type="button" onClick={() => { setClinicalEditing(null); setClinicalCode('development_'); setClinicalName(''); setClinicalOrder('0') }}>Cancel</button>}</form>{clinicalErrorMessage && <p className="inline-error" role="alert">{clinicalErrorMessage}</p>}{clinicalMessage && <p className="inline-success" role="status">{clinicalMessage}</p>}<div className="admin-catalogue-list">{clinicalCatalogue.map(item => <div className="admin-row" key={item.id}><strong>{item.displayName}<small>{item.category} · {item.code}</small></strong><span>{item.active ? 'Active' : 'Inactive'}<small>Order {item.displayOrder}</small></span><span><button className="small-action" type="button" onClick={() => { setClinicalEditing(item.id); setClinicalDomain(item.category as typeof clinicalDomain); setClinicalCode(item.code); setClinicalName(item.displayName); setClinicalOrder(String(item.displayOrder)) }}>Edit</button><button className="small-action" type="button" onClick={() => clinicalActive.mutate(item)} disabled={clinicalActive.isPending}>{item.active ? 'Deactivate' : 'Reactivate'}</button></span></div>)}</div></section>
    </div>
  </div>
}
