import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { useState } from 'react'
import { createFileRoute } from '@tanstack/react-router'
import { Building2, History, Settings, Users } from 'lucide-react'

import { adminAPI } from '../../api/client'
import { sessionQuery } from '../../features/auth/queries'

export const Route = createFileRoute('/_authenticated/admin')({ component: AdminPage })

function settingGroup(key: string) {
  if (key.startsWith('clinic_flow')) return 'Clinic flow'
  if (key.startsWith('theatre_')) return 'Theatre'
  if (key.startsWith('referral_')) return 'Referrals'
  if (key.startsWith('correspondence_')) return 'Correspondence'
  if (key.startsWith('messaging_')) return 'Messaging'
  return 'General'
}

function settingLabel(key: string) {
  return key.replaceAll('_', ' ')
}

function AdminPage() {
  const { data: users = [], isError: usersError } = useQuery({ queryKey: ['admin', 'users'], queryFn: adminAPI.users })
  const { data: contexts, isError: contextsError } = useQuery({ queryKey: ['admin', 'contexts'], queryFn: adminAPI.contexts })
  const { data: settings = [], isError: settingsError } = useQuery({ queryKey: ['admin', 'settings'], queryFn: adminAPI.settings })
  const { data: audit = [], isError: auditError } = useQuery({ queryKey: ['admin', 'audit'], queryFn: adminAPI.audit })
  const { data: catalogue = [], isError: catalogueError } = useQuery({ queryKey: ['admin', 'prescription-catalogue'], queryFn: adminAPI.prescriptionCatalogue })
  const { data: session } = useQuery(sessionQuery)
  const queryClient = useQueryClient()
  const [editing, setEditing] = useState<string | null>(null)
  const [username, setUsername] = useState('')
  const [displayName, setDisplayName] = useState('')
  const [password, setPassword] = useState('')
  const [role, setRole] = useState('clinical_user')
  const [siteId, setSiteId] = useState('')
  const [firmId, setFirmId] = useState('')
  const [userMessage, setUserMessage] = useState<string | null>(null)
  const [userError, setUserError] = useState<string | null>(null)
  const [contextKind, setContextKind] = useState<'site' | 'firm'>('site')
  const [contextID, setContextID] = useState<number | null>(null)
  const [contextName, setContextName] = useState('')
  const [contextMessage, setContextMessage] = useState<string | null>(null)
  const [contextError, setContextError] = useState<string | null>(null)
  const [catalogueEditing, setCatalogueEditing] = useState<number | null>(null)
  const [catalogueCategory, setCatalogueCategory] = useState<'medication' | 'route' | 'frequency' | 'duration' | 'laterality'>('medication')
  const [catalogueCode, setCatalogueCode] = useState('development_')
  const [catalogueName, setCatalogueName] = useState('')
  const [catalogueOrder, setCatalogueOrder] = useState('0')
  const [catalogueMessage, setCatalogueMessage] = useState<string | null>(null)
  const [catalogueErrorMessage, setCatalogueErrorMessage] = useState<string | null>(null)
  const userMutation = useMutation({ mutationFn: ({ id, version, active }: { id: string; version: number; active: boolean }) => adminAPI.setUserActive(id, version, active, session?.csrfToken ?? ''), onSuccess: () => { void queryClient.invalidateQueries({ queryKey: ['admin'] }) } })
  const settingMutation = useMutation({ mutationFn: ({ key, value, version }: { key: string; value: string; version: number }) => adminAPI.updateSetting(key, value, version, session?.csrfToken ?? ''), onSuccess: () => { void queryClient.invalidateQueries({ queryKey: ['admin'] }) } })
  const contextSave = useMutation({ mutationFn: () => { const csrf = session?.csrfToken ?? ''; const version = (contextKind === 'site' ? contexts?.sites : contexts?.firms)?.find(item => item.id === contextID)?.version ?? 0; if (contextKind === 'site') return contextID ? adminAPI.updateSite(contextID, contextName, true, version, csrf) : adminAPI.createSite(contextName, csrf); return contextID ? adminAPI.updateFirm(contextID, contextName, true, version, csrf) : adminAPI.createFirm(contextName, csrf) }, onMutate: () => { setContextMessage(null); setContextError(null) }, onSuccess: () => { setContextID(null); setContextName(''); setContextMessage(`${contextKind === 'site' ? 'Site' : 'Firm'} saved successfully.`); void queryClient.invalidateQueries({ queryKey: ['admin'] }) }, onError: error => setContextError(error instanceof Error ? error.message : 'The organization change could not be saved.') })
  const contextActive = useMutation({ mutationFn: ({ kind, id, name, version, active }: { kind: 'site' | 'firm'; id: number; name: string; version: number; active: boolean }) => kind === 'site' ? adminAPI.setSiteActive(id, name, version, active, session?.csrfToken ?? '') : adminAPI.setFirmActive(id, name, version, active, session?.csrfToken ?? ''), onSuccess: () => { void queryClient.invalidateQueries({ queryKey: ['admin'] }) }, onError: error => setContextError(error instanceof Error ? error.message : 'The organization status could not be changed.') })
  const catalogueSave = useMutation({ mutationFn: () => { const body = { category: catalogueCategory, code: catalogueCode.trim(), displayName: catalogueName.trim(), active: true, displayOrder: Number(catalogueOrder) }; const csrf = session?.csrfToken ?? ''; if (catalogueEditing) return adminAPI.updatePrescriptionCatalogue(catalogueEditing, { ...body, active: catalogue.find(item => item.id === catalogueEditing)?.active ?? true, expectedVersion: catalogue.find(item => item.id === catalogueEditing)?.version ?? 0 }, csrf); return adminAPI.createPrescriptionCatalogue(body, csrf) }, onMutate: () => { setCatalogueMessage(null); setCatalogueErrorMessage(null) }, onSuccess: () => { setCatalogueEditing(null); setCatalogueCode('development_'); setCatalogueName(''); setCatalogueOrder('0'); setCatalogueMessage('Synthetic catalogue item saved successfully.'); void queryClient.invalidateQueries({ queryKey: ['admin', 'prescription-catalogue'] }) }, onError: error => setCatalogueErrorMessage(error instanceof Error ? error.message : 'The synthetic catalogue item could not be saved.') })
  const catalogueActive = useMutation({ mutationFn: (item: typeof catalogue[number]) => adminAPI.updatePrescriptionCatalogue(item.id, { category: item.category, code: item.code, displayName: item.displayName, active: !item.active, displayOrder: item.displayOrder, expectedVersion: item.version }, session?.csrfToken ?? ''), onMutate: () => { setCatalogueMessage(null); setCatalogueErrorMessage(null) }, onSuccess: (_item, item) => { setCatalogueMessage(`Synthetic catalogue item ${item.active ? 'deactivated' : 'reactivated'} successfully.`); void queryClient.invalidateQueries({ queryKey: ['admin', 'prescription-catalogue'] }) }, onError: error => setCatalogueErrorMessage(error instanceof Error ? error.message : 'The synthetic catalogue status could not be changed.') })
  const userSave = useMutation({ mutationFn: () => editing ? adminAPI.updateUser(editing, { username, displayName, password: password || undefined, role, siteIds: siteId ? [Number(siteId)] : [], firmIds: firmId ? [Number(firmId)] : [], expectedVersion: users.find(user => user.id === editing)?.version ?? 0 }, session?.csrfToken ?? '') : adminAPI.createUser({ username, displayName, password, role, siteIds: siteId ? [Number(siteId)] : [], firmIds: firmId ? [Number(firmId)] : [] }, session?.csrfToken ?? ''), onMutate: () => { setUserMessage(null); setUserError(null) }, onSuccess: () => { setEditing(null); setUsername(''); setDisplayName(''); setPassword(''); setRole('clinical_user'); setSiteId(''); setFirmId(''); setUserMessage(editing ? 'Synthetic user updated successfully.' : 'Synthetic user created successfully.'); void queryClient.invalidateQueries({ queryKey: ['admin'] }) }, onError: (error) => { setUserError(error instanceof Error ? error.message : 'The user could not be saved.') } })
  if (!session?.permissions.includes('admin.development.read') || usersError || contextsError || settingsError || auditError || catalogueError) {
    return <div className="admin-workspace"><div className="workspace-title"><p>Administration demonstration</p><h1>Access restricted</h1><span>Your current role cannot view administration settings.</span></div></div>
  }

  return <div className="admin-workspace">
    <div className="workspace-title"><p>Administration demonstration</p><h1>Admin &amp; configuration</h1><span>Seeded synthetic settings and users only. No production records are changed.</span></div>
    <div className="admin-grid">
      <section className="admin-panel"><h2><Users size={18} /> Users</h2>
        <form className="admin-user-form" onSubmit={event => { event.preventDefault(); userSave.mutate() }}>
          <strong>{editing ? 'Edit synthetic user' : 'Create synthetic user'}</strong>
          <label>Username<input required pattern="[a-z0-9._-]+" value={username} onChange={event => setUsername(event.target.value)} /></label>
          <label>Display name<input required value={displayName} onChange={event => setDisplayName(event.target.value)} /></label>
          <label>Password{editing ? ' (optional)' : ''}<input required={!editing} minLength={6} type="password" value={password} onChange={event => setPassword(event.target.value)} /></label>
          <label>Role<select value={role} onChange={event => setRole(event.target.value)}><option value="clinical_user">Clinical user</option><option value="institution_administrator">Institution administrator</option></select></label>
          <label>Site<select value={siteId} onChange={event => setSiteId(event.target.value)}><option value="">No site membership</option>{contexts?.sites.filter(site => site.active !== false).map(site => <option key={site.id} value={site.id}>{site.name}</option>)}</select></label>
          <label>Firm<select value={firmId} onChange={event => setFirmId(event.target.value)}><option value="">No firm membership</option>{contexts?.firms.filter(firm => firm.active !== false).map(firm => <option key={firm.id} value={firm.id}>{firm.name}</option>)}</select></label>
          <span><button className="small-action" type="submit" disabled={userSave.isPending}>{userSave.isPending ? 'Saving…' : editing ? 'Update user' : 'Create user'}</button>{editing && <button className="small-action" type="button" onClick={() => setEditing(null)}>Cancel</button>}</span>
          {userError && <p className="inline-error" role="alert">{userError}</p>}
          {userMessage && <p className="inline-success" role="status">{userMessage}</p>}
        </form>
        {users.map(user => <div className="admin-row" key={user.id}><strong>{user.displayName}<small>{user.username}</small></strong><span>{user.role.replaceAll('_', ' ')}<small>{(user.permissions ?? []).join(', ') || 'No permissions'}</small></span><span>{user.active ? 'Active' : 'Inactive'} <button className="small-action" type="button" onClick={() => userMutation.mutate({ id: user.id, version: user.version, active: !user.active })}>{user.active ? 'Deactivate' : 'Reactivate'}</button> <button className="small-action" type="button" onClick={() => { setEditing(user.id); setUsername(user.username); setDisplayName(user.displayName); setRole(user.role); setPassword(''); setSiteId(String(user.sites?.[0]?.id ?? '')); setFirmId(String(user.firms?.[0]?.id ?? '')) }}>Edit</button></span></div>)}
      </section>
      <section className="admin-panel"><h2><Building2 size={18} /> Organization</h2><p><strong>{contexts?.institution.name}</strong></p><p className="muted">Current context: {session?.context.site.name} / {session?.context.firm.name}</p><form className="admin-context-form" onSubmit={event => { event.preventDefault(); contextSave.mutate() }}><strong>{contextID ? `Edit ${contextKind}` : 'Add synthetic context'}</strong><select aria-label="Context type" value={contextKind} onChange={event => { setContextKind(event.target.value as 'site' | 'firm'); setContextID(null); setContextName('') }}><option value="site">Site</option><option value="firm">Firm</option></select><input aria-label="Context name" required value={contextName} onChange={event => setContextName(event.target.value)} placeholder="Name" /><button className="small-action" type="submit" disabled={contextSave.isPending}>{contextSave.isPending ? 'Saving…' : contextID ? 'Update' : 'Add'}</button>{contextID && <button className="small-action" type="button" onClick={() => { setContextID(null); setContextName('') }}>Cancel</button>}</form>{contextError && <p className="inline-error" role="alert">{contextError}</p>}{contextMessage && <p className="inline-success" role="status">{contextMessage}</p>}<div className="admin-context-list"><strong>Sites</strong>{contexts?.sites.map(item => <div className="admin-row" key={`site-${item.id}`}><span>{item.name}</span><span>{item.active ? 'Active' : 'Inactive'}</span><span><button className="small-action" type="button" onClick={() => { setContextKind('site'); setContextID(item.id); setContextName(item.name) }}>Edit</button><button className="small-action" type="button" onClick={() => contextActive.mutate({ kind: 'site', id: item.id, name: item.name, version: item.version ?? 1, active: !item.active })}>{item.active ? 'Deactivate' : 'Reactivate'}</button></span></div>)}<strong>Firms</strong>{contexts?.firms.map(item => <div className="admin-row" key={`firm-${item.id}`}><span>{item.name}</span><span>{item.active ? 'Active' : 'Inactive'}</span><span><button className="small-action" type="button" onClick={() => { setContextKind('firm'); setContextID(item.id); setContextName(item.name) }}>Edit</button><button className="small-action" type="button" onClick={() => contextActive.mutate({ kind: 'firm', id: item.id, name: item.name, version: item.version ?? 1, active: !item.active })}>{item.active ? 'Deactivate' : 'Reactivate'}</button></span></div>)}</div></section>
      <section className="admin-panel"><h2><Settings size={18} /> Operational configuration</h2>{settings.map((setting, index) => <div key={setting.key}>{(index === 0 || settingGroup(settings[index - 1]?.key ?? '') !== settingGroup(setting.key)) && <h3 className="admin-setting-group">{settingGroup(setting.key)}</h3>}<div className="admin-row"><span>{settingLabel(setting.key)}</span><span>{setting.key === 'default_site' || setting.key === 'default_firm' ? <select aria-label={setting.key} value={setting.value} onChange={event => settingMutation.mutate({ key: setting.key, value: event.target.value, version: setting.version })}>{(setting.key === 'default_site' ? contexts?.sites : contexts?.firms)?.filter(item => item.active).map(item => <option key={item.id} value={item.name}>{item.name}</option>)}</select> : <input aria-label={setting.key} defaultValue={setting.value} onBlur={event => { const value = event.currentTarget.value; if (value !== setting.value) settingMutation.mutate({ key: setting.key, value, version: setting.version }) }} />}</span></div></div>)}</section>
      <section className="admin-panel"><h2><Settings size={18} /> Medication catalogue</h2><p className="muted">Synthetic development catalogue only. Changes affect demonstration drafts, not prescriptions or clinical records.</p><form className="admin-catalogue-form" onSubmit={event => { event.preventDefault(); catalogueSave.mutate() }}><select aria-label="Catalogue category" value={catalogueCategory} onChange={event => setCatalogueCategory(event.target.value as typeof catalogueCategory)}><option value="medication">Medication</option><option value="route">Route</option><option value="frequency">Frequency</option><option value="duration">Duration</option><option value="laterality">Laterality</option></select><input aria-label="Catalogue code" required pattern="development_[a-z0-9_]+" value={catalogueCode} onChange={event => setCatalogueCode(event.target.value)} /><input aria-label="Catalogue display name" required value={catalogueName} onChange={event => setCatalogueName(event.target.value)} placeholder="Display name" /><input aria-label="Catalogue display order" required type="number" min="0" value={catalogueOrder} onChange={event => setCatalogueOrder(event.target.value)} /><button className="small-action" type="submit" disabled={catalogueSave.isPending}>{catalogueSave.isPending ? 'Saving…' : catalogueEditing ? 'Update item' : 'Add item'}</button>{catalogueEditing && <button className="small-action" type="button" onClick={() => { setCatalogueEditing(null); setCatalogueCode('development_'); setCatalogueName(''); setCatalogueOrder('0') }}>Cancel</button>}</form>{catalogueErrorMessage && <p className="inline-error" role="alert">{catalogueErrorMessage}</p>}{catalogueMessage && <p className="inline-success" role="status">{catalogueMessage}</p>}<div className="admin-catalogue-list">{catalogue.map(item => <div className="admin-row" key={item.id}><strong>{item.displayName}<small>{item.category} · {item.code}</small></strong><span>{item.active ? 'Active' : 'Inactive'}<small>Order {item.displayOrder}</small></span><span><button className="small-action" type="button" onClick={() => { setCatalogueEditing(item.id); setCatalogueCategory(item.category); setCatalogueCode(item.code); setCatalogueName(item.displayName); setCatalogueOrder(String(item.displayOrder)) }}>Edit</button><button className="small-action" type="button" onClick={() => catalogueActive.mutate(item)} disabled={catalogueActive.isPending}>{item.active ? 'Deactivate' : 'Reactivate'}</button></span></div>)}</div></section>
      <section className="admin-panel admin-audit-panel"><h2><History size={18} /> Audit history</h2><p className="muted">Append-only record of synthetic administration changes in the current institution.</p>{audit.length === 0 ? <p className="muted">No administration events yet.</p> : <div className="admin-audit-list">{audit.map((event, index) => <article className="admin-audit-event" key={`${event.command}-${event.createdAt}-${index}`}><div><strong>{event.command.replaceAll('.', ' ')}</strong><span className={`audit-outcome audit-${event.outcome}`}>{event.outcome}</span></div><p><strong>Actor:</strong> {event.actorDisplayName} · <strong>Target:</strong> {event.targetDisplayName ?? event.targetKey ?? event.targetType}{event.targetDisplayName && event.targetPublicId ? ` · ${event.targetPublicId}` : ''}</p><p><strong>Changed:</strong> {event.changedFields.join(', ') || 'No fields recorded'}</p><small>{new Date(event.createdAt).toLocaleString()} · Correlation ID: {event.correlationId}</small></article>)}</div>}</section>
    </div>
  </div>
}
